<?php

namespace Tests\Feature;

use App\Models\Category;
use App\Models\Product;
use App\Models\TaxGroup;
use App\Models\Tenant;
use App\Models\User;
use App\Support\BusinessTypes;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Routing\Middleware\ThrottleRequests;
use Tests\TestCase;

/**
 * The golden fixtures the offline pricing engine is measured against.
 *
 * ── Why this is a TEST and not a script ─────────────────────────────────
 *
 * The fixtures are produced by ringing real sales through the real endpoint, so
 * what they record is what the server ACTUALLY charges — not a second
 * implementation of the pricing rules that could be wrong in the same way the
 * first one is. A generator that re-derived the answers would agree with itself
 * forever and prove nothing.
 *
 * Running normally, this file ASSERTS the committed fixtures still match the
 * server. That is the half that matters day to day: change a pricing rule and
 * this goes red, which is the reminder that a till somewhere is now computing
 * the old answer.
 *
 * Run with `SHOPOS_WRITE_FIXTURES=1` it rewrites them instead. Do that
 * deliberately, read the diff, and copy the file to the panel — the two sides
 * are locked together only for as long as somebody keeps them that way.
 *
 * ── Why the rounding cases are here at all ──────────────────────────────
 *
 * PHP's `round($x, 2)` and JavaScript's `Math.round(x * 100) / 100` disagree.
 * Measured, not assumed: of eight ordinary money values, three differ —
 * 1.005, 1.015 and 0.145 all round DOWN in naive JavaScript and UP in PHP.
 * Every one of those is a receipt out by a paisa, and a shop that reconciles
 * its drawer to the paisa would find it.
 *
 * That is also why the offline engine mirrors PHP's float-and-round sequence
 * rather than working in integer paisa. Integer arithmetic is the more correct
 * thing to build and the wrong thing to build here: the goal is not to be
 * right, it is to AGREE with the server, down to the last paisa, on every
 * bill.
 */
class PricingFixturesTest extends TestCase
{
    use RefreshDatabase;

    /** Bumped when the fixture SHAPE changes, so a stale copy is obvious. */
    private const VERSION = 1;

    private Tenant $tenant;

    private User $owner;

    private Category $category;

    protected function setUp(): void
    {
        parent::setUp();
        $this->withoutMiddleware(ThrottleRequests::class);

        $this->tenant = Tenant::factory()->create([
            'setup_completed' => true,
            'business_type' => 'mart',
            'features' => BusinessTypes::defaultFeatures('mart'),
        ]);
        $this->owner = User::factory()->shopOwner($this->tenant)->create();
        $this->category = Category::query()->create([
            'tenant_id' => $this->tenant->id, 'name' => 'Grocery', 'is_active' => true,
        ]);
    }

    private function actingAsOwner(): static
    {
        $token = $this->owner->createToken('t', ['access'])->plainTextToken;
        $this->app['auth']->forgetGuards();

        return $this->withToken($token);
    }

    // ── The fixtures ────────────────────────────────────────────────

    public function test_the_committed_fixtures_still_describe_what_the_server_charges(): void
    {
        $fixtures = [
            'version' => self::VERSION,
            'note' => 'Generated by PricingFixturesTest with SHOPOS_WRITE_FIXTURES=1. Do not hand-edit.',
            'rounding' => $this->roundingCases(),
            'carts' => $this->cartCases(),
        ];

        $path = base_path('tests/fixtures/pricing.json');

        if (env('SHOPOS_WRITE_FIXTURES') === '1') {
            @mkdir(dirname($path), 0755, true);
            file_put_contents($path, json_encode($fixtures, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n");
            $this->addToAssertionCount(1);
            $this->markTestSkipped('Fixtures rewritten. Read the diff, then copy to the panel.');
        }

        $this->assertFileExists($path, 'Run with SHOPOS_WRITE_FIXTURES=1 to create the fixtures.');

        $committed = json_decode((string) file_get_contents($path), true);

        $this->assertSame(self::VERSION, $committed['version'] ?? null,
            'The fixture shape changed. Regenerate and copy to the panel.');

        $this->assertEquals(
            $fixtures,
            $committed,
            "The server no longer charges what the fixtures say.\n\n"
            ."A pricing rule changed. Somewhere a till is computing the OLD answer, and it will keep\n"
            ."doing it until these are regenerated and copied to the panel:\n\n"
            ."    SHOPOS_WRITE_FIXTURES=1 php artisan test --filter=PricingFixturesTest\n",
        );
    }

    /**
     * Money values where PHP and naive JavaScript disagree, plus ordinary ones.
     *
     * The expected side is PHP's answer, recorded rather than reasoned about.
     */
    private function roundingCases(): array
    {
        $values = [
            1.005, 1.015, 0.145, 2.675, 8.475, 0.615, 1.045, 1234.565,
            0.005, 0.015, 2.5, 2.4999, 999999.995, 0.0, 1.0,
            -1.005, -0.145, -2.675,
        ];

        return array_map(static fn (float $v): array => [
            'value' => $v,
            'expected' => round($v, 2),
        ], $values);
    }

    /**
     * Whole carts, rung through the real endpoint.
     *
     * Each names the rule it pins, because a fixture nobody can explain is a
     * fixture nobody dares change.
     */
    private function cartCases(): array
    {
        return [
            $this->cart('a plain line, tax on top', [
                ['price' => 250, 'tax_rate' => 17, 'quantity' => 2],
            ]),

            $this->cart('a sale price beats the regular price', [
                ['price' => 250, 'discount_price' => 199, 'tax_rate' => 0, 'quantity' => 1],
            ]),

            $this->cart('a sale price ABOVE the regular price is ignored', [
                ['price' => 200, 'discount_price' => 250, 'tax_rate' => 0, 'quantity' => 1],
            ]),

            $this->cart('a quantity tier the cart qualifies for', [
                [
                    'price' => 100, 'tax_rate' => 0, 'quantity' => 12,
                    'price_tiers' => [['min_qty' => 10, 'price' => 90], ['min_qty' => 50, 'price' => 80]],
                ],
            ]),

            $this->cart('a quantity below every tier pays full price', [
                [
                    'price' => 100, 'tax_rate' => 0, 'quantity' => 3,
                    'price_tiers' => [['min_qty' => 10, 'price' => 90]],
                ],
            ]),

            $this->cart('a NON-MONOTONIC tier set charges the cheapest qualifying break', [
                [
                    // The request layer refuses tiers like these, so they can
                    // only arrive as legacy data — which is exactly the case
                    // priceForQty guards. These fixtures build products through
                    // the model rather than the API, so the guard is reachable.
                    //
                    // At qty 25 both breaks qualify and the DEEPER one is
                    // dearer. Charging the deepest would overcharge by 20 a
                    // unit; the rule is cheapest-qualifying, and without a
                    // fixture like this the two are indistinguishable.
                    'price' => 100, 'tax_rate' => 0, 'quantity' => 25,
                    'price_tiers' => [['min_qty' => 10, 'price' => 70], ['min_qty' => 20, 'price' => 90]],
                ],
            ]),

            $this->cart('a sale price deeper than the tier still wins', [
                [
                    'price' => 100, 'discount_price' => 85, 'tax_rate' => 0, 'quantity' => 20,
                    'price_tiers' => [['min_qty' => 10, 'price' => 90]],
                ],
            ]),

            $this->cart('a weighed item, three decimal places', [
                ['price' => 320, 'tax_rate' => 0, 'quantity' => 1.234, 'sold_by' => 'weight'],
            ]),

            $this->cart('a weighed item whose line lands on a rounding edge', [
                ['price' => 2.5, 'tax_rate' => 0, 'quantity' => 1.234, 'sold_by' => 'weight'],
            ]),

            $this->cart('tax INSIDE the price, not added to it', [
                ['price' => 117, 'tax_rate' => 17, 'quantity' => 1],
            ], ['tax_inclusive' => true]),

            $this->cart('inclusive tax across two lines at one rate', [
                ['price' => 117, 'tax_rate' => 17, 'quantity' => 2],
                ['price' => 58.5, 'tax_rate' => 17, 'quantity' => 3],
            ], ['tax_inclusive' => true]),

            $this->cart('two lines at DIFFERENT tax rates', [
                ['price' => 100, 'tax_rate' => 17, 'quantity' => 1],
                ['price' => 100, 'tax_rate' => 5, 'quantity' => 1],
            ]),

            $this->cart('a zero-rated line beside a taxed one', [
                ['price' => 100, 'tax_rate' => 0, 'quantity' => 1],
                ['price' => 100, 'tax_rate' => 17, 'quantity' => 1],
            ]),

            $this->cart('a tax GROUP overrides the item rate', [
                ['price' => 100, 'tax_rate' => 5, 'tax_group_rate' => 18, 'quantity' => 1],
            ]),

            $this->cart('the shop default applies when an item has no rate', [
                ['price' => 100, 'tax_rate' => null, 'quantity' => 1],
            ], ['default_tax_rate' => 12]),

            $this->cart('a whole-cart discount, spread across the tax', [
                ['price' => 100, 'tax_rate' => 17, 'quantity' => 5],
            ], [], ['discount' => 100]),

            $this->cart('a discount that swallows the whole cart', [
                ['price' => 100, 'tax_rate' => 17, 'quantity' => 1],
            ], [], ['discount' => 100]),

            $this->cart('a per-line discount by percentage', [
                ['price' => 200, 'tax_rate' => 0, 'quantity' => 2, 'line_discount_pct' => 10],
            ]),

            $this->cart('a per-line discount by amount', [
                ['price' => 200, 'tax_rate' => 0, 'quantity' => 2, 'line_discount' => 55],
            ]),

            $this->cart('a line discount clamped to the line it sits on', [
                ['price' => 100, 'tax_rate' => 0, 'quantity' => 1, 'line_discount' => 500],
            ]),

            $this->cart('a line discount and tax together', [
                ['price' => 200, 'tax_rate' => 17, 'quantity' => 3, 'line_discount_pct' => 25],
            ]),

            $this->cart('wholesale price level', [
                ['price' => 100, 'wholesale_price' => 80, 'tax_rate' => 0, 'quantity' => 4, 'price_level' => 'wholesale'],
            ]),

            $this->cart('wholesale never charges more than retail', [
                ['price' => 100, 'wholesale_price' => 120, 'tax_rate' => 0, 'quantity' => 4, 'price_level' => 'wholesale'],
            ]),

            $this->cart('three lines, mixed rates, a cart discount and inclusive tax', [
                ['price' => 349.99, 'tax_rate' => 17, 'quantity' => 3],
                ['price' => 75.5, 'tax_rate' => 5, 'quantity' => 7],
                ['price' => 12.25, 'tax_rate' => 0, 'quantity' => 11],
            ], ['tax_inclusive' => true], ['discount' => 137.4]),

            $this->cart('the float trap: a cart whose naive sum ends .30000000000000004', [
                ['price' => 0.1, 'tax_rate' => 0, 'quantity' => 1],
                ['price' => 0.2, 'tax_rate' => 0, 'quantity' => 1],
            ]),

            $this->cart('a rounding-edge unit price at an awkward quantity', [
                ['price' => 1.005, 'tax_rate' => 0, 'quantity' => 3],
                ['price' => 0.145, 'tax_rate' => 0, 'quantity' => 7],
            ]),
        ];
    }

    /**
     * Ring one cart through the real endpoint and record what it charged.
     */
    private function cart(string $name, array $items, array $settings = [], array $sale = []): array
    {
        $this->tenant->forceFill(['settings' => $settings])->save();

        $products = [];
        $payloadItems = [];
        $inputItems = [];

        foreach ($items as $index => $spec) {
            $taxGroupId = null;
            if (isset($spec['tax_group_rate'])) {
                $taxGroupId = TaxGroup::query()->create([
                    'tenant_id' => $this->tenant->id,
                    'name' => "Group {$name} {$index}",
                    'rate' => $spec['tax_group_rate'],
                    'is_active' => true,
                ])->id;
            }

            $product = Product::query()->create([
                'tenant_id' => $this->tenant->id,
                'category_id' => $this->category->id,
                'type' => 'product',
                'item_type' => 'physical_product',
                'name' => "Fixture {$name} {$index}",
                'price' => $spec['price'],
                'discount_price' => $spec['discount_price'] ?? null,
                'wholesale_price' => $spec['wholesale_price'] ?? null,
                'price_tiers' => $spec['price_tiers'] ?? null,
                'tax_rate' => $spec['tax_rate'] ?? null,
                'tax_group_id' => $taxGroupId,
                'sold_by' => $spec['sold_by'] ?? 'unit',
                'track_inventory' => false,
                'is_active' => true,
            ]);
            $products[] = $product;

            $line = ['product_id' => $product->id, 'quantity' => $spec['quantity']];
            // The API's own names. An earlier version of this file used
            // `discount_percent` and `discount_amount`, which the request
            // simply ignores — so two fixtures claimed to cover line discounts
            // and exercised nothing at all. A fixture that silently tests
            // nothing is worse than no fixture, because it reads as coverage.
            if (isset($spec['line_discount_pct'])) {
                $line['line_discount_pct'] = $spec['line_discount_pct'];
            }
            if (isset($spec['line_discount'])) {
                $line['line_discount'] = $spec['line_discount'];
            }
            if (isset($spec['price_level'])) {
                $line['price_level'] = $spec['price_level'];
            }
            $payloadItems[] = $line;

            // What the offline engine will be handed: the catalog projection
            // fields plus the cart line, with no product id — an engine that
            // needed one would be reading a database rather than pricing.
            $inputItems[] = [
                'price' => (float) $spec['price'],
                'discount_price' => isset($spec['discount_price']) ? (float) $spec['discount_price'] : null,
                'wholesale_price' => isset($spec['wholesale_price']) ? (float) $spec['wholesale_price'] : null,
                'price_tiers' => $spec['price_tiers'] ?? null,
                'tax_rate' => isset($spec['tax_rate']) ? (float) $spec['tax_rate'] : null,
                'tax_group_rate' => isset($spec['tax_group_rate']) ? (float) $spec['tax_group_rate'] : null,
                'sold_by' => $spec['sold_by'] ?? 'unit',
                'quantity' => (float) $spec['quantity'],
                'price_level' => $spec['price_level'] ?? 'retail',
                'line_discount_pct' => isset($spec['line_discount_pct']) ? (float) $spec['line_discount_pct'] : null,
                'line_discount' => isset($spec['line_discount']) ? (float) $spec['line_discount'] : null,
            ];
        }

        $payload = array_merge([
            'channel' => 'pos',
            'payment_method' => 'cash',
            'items' => $payloadItems,
            'amount_paid' => 1_000_000,
        ], $sale);

        $data = $this->actingAsOwner()->postJson('/api/v1/sales', $payload)
            ->assertCreated()->json('data');

        return [
            'name' => $name,
            'input' => [
                'settings' => [
                    'tax_inclusive' => (bool) ($settings['tax_inclusive'] ?? false),
                    'default_tax_rate' => (float) ($settings['default_tax_rate'] ?? 0),
                    'cash_rounding' => (int) ($settings['cash_rounding'] ?? 0),
                ],
                'items' => $inputItems,
                'discount' => (float) ($sale['discount'] ?? 0),
            ],
            'expected' => [
                'subtotal' => (float) $data['subtotal'],
                'discount' => (float) $data['discount'],
                'tax' => (float) $data['tax'],
                'total' => (float) $data['total'],
                'lines' => array_map(static fn (array $line): array => [
                    'unit_price' => (float) $line['unit_price'],
                    'line_total' => (float) $line['line_total'],
                    'tax_rate' => (float) $line['tax_rate'],
                ], $data['items']),
            ],
        ];
    }
}
