<?php

namespace Tests\Feature;

use App\Models\Customer;
use App\Models\CustomerGroup;
use App\Models\Product;
use App\Models\TaxGroup;
use App\Models\Tenant;
use App\Models\User;
use App\Support\BusinessTypes;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Routing\Middleware\ThrottleRequests;
use Tests\TestCase;

/**
 * WHOLE BILLS, as the counter screen has to make them.
 *
 * `PricingFixturesTest` holds the OFFLINE engine to the server: lines, a
 * keyed discount, a promotion, tax. The counter screen makes a longer bill
 * than that — it also has to know what the customer's group is owed, what
 * points are worth, what a traded-in battery settles, and which coin a cash
 * sale lands on. None of those had a fixture, and three of them were wrong:
 *
 *     the group's percentage   not on the screen at all
 *     the group's price level  not on the screen at all
 *     cash beside a trade-in   rounded on screen, exact on the server
 *
 * So this file rings each of those through the real endpoint and writes down
 * what came back, and the panel prices the same carts with the functions the
 * screen calls. Same arrangement as the other fixtures and for the same
 * reason: a generator that re-derived the answers would agree with itself
 * for ever.
 *
 * ── How a case is rung ───────────────────────────────────────────────
 *
 * Twice. First with nothing tendered, which the server refuses while stating
 * the bill — that statement is `payable`, the figure a till shows. Then with
 * exactly that figure, declared as `expected_payable`, which must complete
 * with no change. A case that cannot be paid to the paisa with the figure
 * the server itself gave would fail here, before any till is involved.
 *
 * Run with `SHOPOS_WRITE_FIXTURES=1` to rewrite, then copy to the panel:
 *
 *     cp tests/fixtures/till-bill.json ../panel/src/modules/pos/fixtures/
 */
class TillBillFixturesTest extends TestCase
{
    use RefreshDatabase;

    private const VERSION = 2;

    private Tenant $tenant;

    private User $owner;

    private int $serial = 0;

    protected function setUp(): void
    {
        parent::setUp();
        $this->withoutMiddleware(ThrottleRequests::class);

        $this->tenant = Tenant::factory()->create([
            'setup_completed' => true,
            'business_type' => 'mart',
            'features' => BusinessTypes::defaultFeatures('mart'),
        ]);
        $this->owner = User::factory()->shopOwner($this->tenant)->create();
    }

    private function asOwner(): static
    {
        $token = $this->owner->createToken('t', ['access'])->plainTextToken;
        $this->app['auth']->forgetGuards();

        return $this->withToken($token);
    }

    public function test_the_committed_bills_are_still_what_the_server_charges(): void
    {
        $fixtures = [
            'version' => self::VERSION,
            'note' => 'Generated by TillBillFixturesTest with SHOPOS_WRITE_FIXTURES=1. Do not hand-edit.',
            'bills' => $this->bills(),
        ];

        $path = base_path('tests/fixtures/till-bill.json');

        if (env('SHOPOS_WRITE_FIXTURES') === '1') {
            file_put_contents($path, json_encode($fixtures, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n");
            $this->addToAssertionCount(1);
            $this->markTestSkipped('Fixtures rewritten. Read the diff, then copy to the panel.');
        }

        $this->assertFileExists($path, 'Run with SHOPOS_WRITE_FIXTURES=1 to create the fixtures.');

        $committed = json_decode((string) file_get_contents($path), true);

        $this->assertSame(self::VERSION, $committed['version'] ?? null,
            'The fixture shape changed. Regenerate and copy to the panel.');

        $this->assertEquals(
            $fixtures,
            $committed,
            "The server no longer makes these bills the way the fixtures say.\n\n"
            ."The counter screen is still making them the OLD way, and will be refused or corrected\n"
            ."on every such sale until these are regenerated and copied to the panel:\n\n"
            ."    SHOPOS_WRITE_FIXTURES=1 php artisan test --filter=TillBillFixturesTest\n"
            ."    cp tests/fixtures/till-bill.json ../panel/src/modules/pos/fixtures/\n",
        );
    }

    /** Each names the rule it pins. A fixture nobody can explain is one nobody dares change. */
    private function bills(): array
    {
        $taxed = ['price' => 4200, 'tax_group_rate' => 18, 'quantity' => 1];

        return [
            $this->bill('a taxed line on a card, nobody special', [$taxed]),

            // ── What a customer's group is owed ─────────────────────
            $this->bill('a member\'s percentage comes off before the tax', [$taxed],
                group: ['price_level' => 'retail', 'discount_percent' => 10]),

            $this->bill('a member\'s percentage is taken on what the keyed discount left', [$taxed],
                sale: ['discount' => 200],
                group: ['price_level' => 'retail', 'discount_percent' => 10]),

            $this->bill('a member\'s percentage on a bill that does not divide', [
                ['price' => 1333.33, 'tax_rate' => 17, 'quantity' => 3],
                ['price' => 49.99, 'tax_rate' => 0, 'quantity' => 7],
            ], group: ['price_level' => 'retail', 'discount_percent' => 7.5]),

            $this->bill('a percentage over a hundred takes the bill to nothing and no further', [
                ['price' => 500, 'tax_rate' => 17, 'quantity' => 1],
            ], group: ['price_level' => 'retail', 'discount_percent' => 100]),

            $this->bill('a trade group rings every unmarked line at wholesale', [
                ['price' => 1000, 'wholesale_price' => 900, 'tax_rate' => 0, 'quantity' => 10],
                ['price' => 250, 'wholesale_price' => 212.5, 'tax_rate' => 17, 'quantity' => 4],
            ], group: ['price_level' => 'wholesale', 'discount_percent' => 0]),

            $this->bill('a trade group leaves alone what has no wholesale price', [
                ['price' => 1000, 'wholesale_price' => 900, 'tax_rate' => 0, 'quantity' => 2],
                ['price' => 80, 'tax_rate' => 0, 'quantity' => 5],
            ], group: ['price_level' => 'wholesale', 'discount_percent' => 0]),

            $this->bill('a line the cashier put back to retail stays there', [
                ['price' => 1000, 'wholesale_price' => 900, 'tax_rate' => 0, 'quantity' => 2, 'price_level' => 'retail'],
                ['price' => 600, 'wholesale_price' => 500, 'tax_rate' => 0, 'quantity' => 1],
            ], group: ['price_level' => 'wholesale', 'discount_percent' => 0]),

            $this->bill('a trade group with a percentage as well, on taxed goods', [
                ['price' => 6310, 'wholesale_price' => 5990, 'tax_group_rate' => 10, 'quantity' => 2],
                ['price' => 2100, 'tax_rate' => 5, 'quantity' => 1],
            ], group: ['price_level' => 'wholesale', 'discount_percent' => 5]),

            $this->bill('at wholesale a quantity break still wins when it is cheaper', [
                [
                    'price' => 100, 'wholesale_price' => 95, 'tax_rate' => 0, 'quantity' => 60,
                    'price_tiers' => [['min_qty' => 10, 'price' => 97], ['min_qty' => 50, 'price' => 90]],
                ],
            ], group: ['price_level' => 'wholesale', 'discount_percent' => 0]),

            $this->bill('a member\'s percentage after a line was already marked down', [
                ['price' => 800, 'tax_rate' => 17, 'quantity' => 3, 'line_discount_pct' => 12.5],
                ['price' => 150, 'tax_rate' => 0, 'quantity' => 2, 'line_discount' => 40],
            ], group: ['price_level' => 'retail', 'discount_percent' => 10]),

            $this->bill('prices that already hold their tax, to a member', [
                ['price' => 1170, 'tax_rate' => 17, 'quantity' => 2],
            ], settings: ['tax_inclusive' => true], group: ['price_level' => 'retail', 'discount_percent' => 10]),

            // ── Points ──────────────────────────────────────────────
            $this->bill('points pay for what the member discount left', [
                ['price' => 2000, 'tax_rate' => 17, 'quantity' => 1],
            ],
                settings: ['loyalty_enabled' => true, 'loyalty_redeem_value' => 2],
                sale: ['redeem_points' => 150],
                group: ['price_level' => 'retail', 'discount_percent' => 10],
                points: 500),

            // ── Coins that exist ────────────────────────────────────
            $this->bill('cash settles down to the ten', [
                ['price' => 1234, 'tax_rate' => 0, 'quantity' => 1],
            ], settings: ['cash_rounding' => 10], sale: ['payment_method' => 'cash']),

            $this->bill('cash settles up to the ten', [
                ['price' => 1236, 'tax_rate' => 0, 'quantity' => 1],
            ], settings: ['cash_rounding' => 10], sale: ['payment_method' => 'cash']),

            $this->bill('a tie goes down, in the customer\'s favour', [
                ['price' => 1235, 'tax_rate' => 0, 'quantity' => 1],
            ], settings: ['cash_rounding' => 10], sale: ['payment_method' => 'cash']),

            $this->bill('a card is never rounded', [
                ['price' => 1234, 'tax_rate' => 0, 'quantity' => 1],
            ], settings: ['cash_rounding' => 10]),

            // 1,234.56 + 209.88 = 1,444.44, which no coin pays.
            $this->bill('paisa from tax settle to the rupee on cash', [
                ['price' => 1234.56, 'tax_rate' => 17, 'quantity' => 1],
            ], settings: ['cash_rounding' => 1], sale: ['payment_method' => 'cash']),

            $this->bill('a member paying cash: the percentage first, then the coin', [
                ['price' => 1234, 'tax_rate' => 17, 'quantity' => 1],
            ],
                settings: ['cash_rounding' => 5],
                sale: ['payment_method' => 'cash'],
                group: ['price_level' => 'retail', 'discount_percent' => 7.5]),

            // ── A tip ───────────────────────────────────────────────
            //
            // The counter never asked for one: the switch in Settings was
            // read by the dine-in tab and nothing else, so a salon that
            // turned it on got no box. These are the bills it now has to make.
            $this->bill('a tip on a card is handed over with the bill, and is not the bill', [
                ['price' => 1000, 'tax_rate' => 5, 'quantity' => 1],
            ], sale: ['tip_amount' => 50]),

            // 1,234 + 25 = 1,259, which settles UP to 1,260: the coin is found
            // on what crosses the counter, tip and all. Rounding the bill
            // first and adding the tip after would make it 1,230 + 25 = 1,255
            // — which is why the tip here is not a round ten. With a tip of
            // 20 both orders give 1,250, and the fixture would prove nothing.
            $this->bill('cash with a tip finds its coin after the tip', [
                ['price' => 1234, 'tax_rate' => 0, 'quantity' => 1],
            ], settings: ['cash_rounding' => 10], sale: ['payment_method' => 'cash', 'tip_amount' => 25]),

            $this->bill('a member\'s percentage comes off the bill, never off the tip', [
                ['price' => 2000, 'tax_rate' => 17, 'quantity' => 1],
            ], sale: ['tip_amount' => 100], group: ['price_level' => 'retail', 'discount_percent' => 10]),

            // ── Goods on the counter ────────────────────────────────
            $this->bill('a trade-in settles part of a card bill', [
                ['price' => 24500, 'tax_rate' => 17, 'quantity' => 1],
            ], tradeIn: 3000),

            $this->bill('cash beside a trade-in is NOT rounded', [
                ['price' => 1234, 'tax_rate' => 0, 'quantity' => 1],
            ], settings: ['cash_rounding' => 10], sale: ['payment_method' => 'cash'], tradeIn: 200),

            $this->bill('a member with a trade-in, paying cash', [
                ['price' => 24567, 'tax_rate' => 17, 'quantity' => 1],
            ],
                settings: ['cash_rounding' => 10],
                sale: ['payment_method' => 'cash'],
                group: ['price_level' => 'retail', 'discount_percent' => 5],
                tradeIn: 3000),
        ];
    }

    /**
     * @param  array<int, array<string, mixed>>  $items
     * @param  array<string, mixed>  $settings
     * @param  array<string, mixed>  $sale
     * @param  array{price_level: string, discount_percent: float|int}|null  $group
     */
    private function bill(
        string $name,
        array $items,
        array $settings = [],
        array $sale = [],
        ?array $group = null,
        float $tradeIn = 0,
        int $points = 0,
    ): array {
        $n = ++$this->serial;
        $this->tenant->forceFill(['settings' => $settings])->save();

        // ── The customer, when the bill depends on who is buying ─────
        $phone = null;
        if ($group !== null || $points > 0) {
            $phone = '0300'.str_pad((string) $n, 7, '0', STR_PAD_LEFT);
            $groupId = $group === null ? null : CustomerGroup::query()->create([
                'tenant_id' => $this->tenant->id, 'name' => "Group {$n}", 'is_active' => true,
                'price_level' => $group['price_level'], 'discount_percent' => $group['discount_percent'],
            ])->id;

            Customer::query()->create([
                'tenant_id' => $this->tenant->id, 'name' => "Customer {$n}", 'phone' => $phone,
                'customer_group_id' => $groupId, 'loyalty_points' => $points,
            ]);
        }

        // ── The shelf ───────────────────────────────────────────────
        $payloadItems = [];
        $inputItems = [];

        foreach ($items as $index => $spec) {
            $taxGroupId = isset($spec['tax_group_rate'])
                ? TaxGroup::query()->create([
                    'tenant_id' => $this->tenant->id, 'name' => "Tax {$n} {$index}",
                    'rate' => $spec['tax_group_rate'], 'is_active' => true,
                ])->id
                : null;

            $product = Product::query()->create([
                'tenant_id' => $this->tenant->id, 'type' => 'product', 'item_type' => 'physical_product',
                'name' => "Bill {$n} item {$index}",
                'price' => $spec['price'],
                'discount_price' => $spec['discount_price'] ?? null,
                'wholesale_price' => $spec['wholesale_price'] ?? null,
                'price_tiers' => $spec['price_tiers'] ?? null,
                'tax_rate' => $spec['tax_rate'] ?? null,
                'tax_group_id' => $taxGroupId,
                'track_inventory' => false, 'is_active' => true,
            ]);

            $line = ['product_id' => $product->id, 'quantity' => $spec['quantity']];
            foreach (['line_discount_pct', 'line_discount', 'price_level'] as $key) {
                if (isset($spec[$key])) {
                    $line[$key] = $spec[$key];
                }
            }
            $payloadItems[] = $line;

            $inputItems[] = [
                'price' => (float) $spec['price'],
                'discount_price' => isset($spec['discount_price']) ? (float) $spec['discount_price'] : null,
                'wholesale_price' => isset($spec['wholesale_price']) ? (float) $spec['wholesale_price'] : null,
                'price_tiers' => $spec['price_tiers'] ?? null,
                'tax_rate' => isset($spec['tax_rate']) ? (float) $spec['tax_rate'] : null,
                'tax_group_rate' => isset($spec['tax_group_rate']) ? (float) $spec['tax_group_rate'] : null,
                'quantity' => (float) $spec['quantity'],
                'line_discount_pct' => isset($spec['line_discount_pct']) ? (float) $spec['line_discount_pct'] : null,
                'line_discount' => isset($spec['line_discount']) ? (float) $spec['line_discount'] : null,
                // What the CASHIER chose, or null for a line left to follow
                // the customer. The till has to arrive at the same level
                // either way, and say which it used.
                'price_level' => $spec['price_level'] ?? null,
            ];
        }

        $payload = array_merge([
            'channel' => 'pos',
            'payment_method' => 'card',
            'items' => $payloadItems,
        ], $sale, $phone === null ? [] : ['customer_phone' => $phone]);

        if ($tradeIn > 0) {
            $scrap = Product::query()->create([
                'tenant_id' => $this->tenant->id, 'type' => 'product', 'item_type' => 'physical_product',
                'name' => "Scrap {$n}", 'price' => 100, 'cost' => 0,
                'track_inventory' => true, 'stock_quantity' => 0, 'is_active' => true,
            ]);
            $payload['trade_ins'] = [['product_id' => $scrap->id, 'quantity' => 1, 'unit_allowance' => $tradeIn]];
        }

        // ── Rung once with nothing, to be TOLD the bill ─────────────
        $stated = $this->asOwner()->postJson('/api/v1/sales', $payload + ['amount_paid' => 0]);

        if ($stated->status() === 422) {
            $figures = $stated->json('meta');
            $this->assertSame('PAYMENT_INSUFFICIENT', $figures['error_code'] ?? null,
                "[{$name}] was refused for something other than being unpaid: ".$stated->getContent());
            $payable = (float) $figures['payable'];
            $rounding = (float) $figures['rounding'];
        } else {
            // A bill of nothing is paid by nothing, and is a sale already.
            $stated->assertCreated();
            $payable = 0.0;
            $rounding = 0.0;
        }

        // ── And once with exactly that, which must be a sale ────────
        $data = $stated->status() === 201
            ? $stated->json('data')
            : $this->asOwner()->postJson('/api/v1/sales', $payload + [
                'amount_paid' => $payable, 'expected_payable' => $payable,
            ])->assertCreated()->json('data');

        $this->assertEqualsWithDelta(0.0, (float) $data['change_due'], 0.001,
            "[{$name}] the server's own figure did not settle the bill exactly");

        return [
            'name' => $name,
            'input' => [
                'settings' => [
                    'default_tax_rate' => (float) ($settings['default_tax_rate'] ?? 0),
                    'tax_inclusive' => (bool) ($settings['tax_inclusive'] ?? false),
                    'cash_rounding' => (int) ($settings['cash_rounding'] ?? 0),
                    'loyalty_redeem_value' => (float) ($settings['loyalty_redeem_value'] ?? 1),
                ],
                'items' => $inputItems,
                'group' => $group === null ? null : [
                    'price_level' => $group['price_level'],
                    'discount_percent' => (float) $group['discount_percent'],
                ],
                'discount' => (float) ($sale['discount'] ?? 0),
                'redeem_points' => (int) ($sale['redeem_points'] ?? 0),
                'method' => $payload['payment_method'],
                'trade_in' => (float) $tradeIn,
                // The staff's, handed over with the bill. Not part of it.
                'tip' => (float) ($sale['tip_amount'] ?? 0),
            ],
            'expected' => [
                'lines' => array_map(static fn (array $line): array => [
                    'unit_price' => (float) $line['unit_price'],
                    'line_total' => (float) $line['line_total'],
                    'tax_rate' => (float) $line['tax_rate'],
                ], $data['items']),
                'subtotal' => (float) $data['subtotal'],
                'discount' => (float) $data['discount'],
                'tax' => (float) $data['tax'],
                'total' => (float) $data['total'],
                // What crosses the counter in rupees — the figure on the screen.
                'payable' => $payable,
                'rounding' => $rounding,
            ],
        ];
    }
}
