<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * The physical thing a till runs on — a tablet, a laptop, a browser profile.
 *
 * A register is a PLACE ("Lane 1"); a device is a THING. Two tablets can serve
 * one lane, and a tablet can be carried between lanes, so the two are not the
 * same identity and one cannot stand in for the other. The distinction only
 * starts to matter with offline selling, where the queue of unsent sales lives
 * on the device: "how long has this been out of contact" and "whose unsent
 * sales are these" are both device questions, not lane questions.
 *
 * `last_seen_at` is the whole point of the table. It is the clock the offline
 * policy reads: days since a device last reached the server.
 *
 * DELIBERATELY NOT a credential yet. The id is generated by the client and
 * registered through an already-authenticated request, so it identifies a
 * device without authorising anything — every route still asks Sanctum. It
 * becomes a credential when offline selling lands and a device must prove
 * itself with no user session behind it; that adds a secret, and adding one now
 * would be an unused key on every till.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('pos_devices', function (Blueprint $table): void {
            // Client-generated: the browser mints it once, stores it, and sends
            // the same one forever. That makes registration idempotent without
            // a round trip to find out whether this device is already known.
            $table->uuid('id')->primary();
            $table->foreignUuid('tenant_id')->constrained('tenants')->cascadeOnDelete();
            // Where it usually sits. Both nullable: a device may be registered
            // before it is assigned a lane, and a shop with one counter has no
            // register rows at all.
            $table->foreignUuid('branch_id')->nullable()->constrained('branches')->nullOnDelete();
            $table->foreignUuid('register_id')->nullable()->constrained('registers')->nullOnDelete();
            // What a human calls it — "Counter tablet", "Ali's laptop". Named by
            // the shop, because "Chrome 141 on Android 14" identifies nothing
            // when three identical tablets sit on three counters.
            $table->string('name')->nullable();
            $table->string('user_agent', 400)->nullable();
            $table->string('platform', 40)->nullable();   // web | android | ios
            // The offline clock. Set on registration and on every touch.
            $table->timestamp('last_seen_at')->nullable();
            // Retired or lost. A revoked device keeps its row: the sales it
            // already sent still point at it, and a deleted row would orphan
            // them. Revocation stops it being used, it does not erase history.
            $table->timestamp('revoked_at')->nullable();
            $table->foreignUuid('revoked_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();

            $table->index(['tenant_id', 'revoked_at']);
            $table->index(['tenant_id', 'last_seen_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('pos_devices');
    }
};
