/**
 * Rounding money the way the server does — which is not the way JavaScript does.
 *
 * ── The measurement that decided this ───────────────────────────────────
 *
 * PHP's `round($x, 2)` and JavaScript's `Math.round(x * 100) / 100` disagree on
 * ordinary money. Of eight everyday values tried, three differ:
 *
 *     1.005   PHP 1.01    naive JS 1.00
 *     1.015   PHP 1.02    naive JS 1.01
 *     0.145   PHP 0.15    naive JS 0.14
 *
 * Every one of those is a receipt out by a paisa. A shop reconciling its drawer
 * would find it, would not be able to explain it, and would be right not to
 * trust the till afterwards.
 *
 * The cause is representation, not arithmetic: 1.005 is not really 1.005, it is
 * 1.00499999999999989…, so multiplying by 100 gives 100.49999999999999 and
 * `Math.round` correctly rounds it down. PHP applies a precision correction
 * first, which lands on 100.5 and rounds up.
 *
 * ── Why mirror it rather than do it properly ────────────────────────────
 *
 * Integer paisa would be the more correct thing to build, and the wrong thing
 * to build here. This engine's job is not to be right — it is to AGREE with the
 * server, to the paisa, on every bill a shop rings. An engine that rounded
 * "better" would disagree, and every disagreement is a variance report nobody
 * can explain and a customer holding a receipt that does not match.
 *
 * So: the same sequence of operations, in the same order, with the same
 * rounding. The golden fixtures are generated by ringing real sales through the
 * real endpoint precisely so this claim is checked rather than believed.
 */

/**
 * Round to 2 decimal places exactly as PHP's `round($value, 2)` does.
 *
 * `toPrecision(15)` is the correction. Fifteen significant digits is inside the
 * ~15.95 a double can carry, so it collapses the representation error
 * (100.49999999999999 → "100.500000000000") without touching any value that was
 * genuinely that precise. Then half-away-from-zero, which is PHP's rule and not
 * `Math.round`'s — `Math.round(-0.5)` is `-0`, PHP's is `-1`.
 */
export function round2(value: number): number {
  if (!Number.isFinite(value)) return value;

  const scaled = Number((value * 100).toPrecision(15));
  const rounded = scaled < 0 ? -Math.round(-scaled) : Math.round(scaled);

  // `+ 0` normalises -0 to 0. A receipt reading "-0.00" is a support call.
  return rounded / 100 + 0;
}

/**
 * Add money and round once, which is what the server does at every step.
 *
 * Not a convenience: the server accumulates a subtotal as
 * `round($subtotal + $lineTotal, 2)` per line, so rounding only at the end
 * would drift from it on carts with many lines.
 */
export function addMoney(a: number, b: number): number {
  return round2(a + b);
}
