import { bestPromotion, type PromoResult } from "./bestPromotion";
import { round2 } from "./money";
import type { CatalogPromotion } from "../sync/catalogService";

/**
 * Pricing a cart with no server.
 *
 * A MIRROR of `CreateSaleAction`, deliberately, down to the order it rounds in.
 * Where the two could differ they must not, so this file follows the server's
 * sequence step for step rather than doing the same arithmetic a tidier way:
 * the server rounds the unit price, then the gross, then the line total, then
 * accumulates the subtotal rounding at every addition. Rounding once at the end
 * gives a different answer on a long cart, and a different answer is a receipt
 * that does not match.
 *
 * The golden fixtures in `fixtures/pricing.json` are generated by ringing real
 * sales through the real endpoint, so the claim that these agree is checked on
 * every CI run rather than asserted here in a comment.
 *
 * ── What this deliberately does NOT do ──────────────────────────────────
 *
 * Coupons, loyalty redemption and customer-group discounts are absent, and that
 * is the offline allow-list rather than an omission. Each is shared state — a
 * coupon that may be used once, a points balance, a group whose discount the
 * shop can change — and a till cannot decide any of them alone. They stay
 * online, so this engine never has to guess at them.
 *
 * Promotions ARE here, as of the first real shadow run — see `bestPromotion`.
 * They were the exception all along: an automatic promotion is a rule the shop
 * wrote down in advance, the same for every till, with nothing to reserve and
 * nothing to race over. A single till can decide it alone, which is the only
 * test that matters. What kept them out was that nobody had mirrored them yet,
 * and the shadow check found the cost of that on its first day: nine carts,
 * every one ten per cent high.
 */

export type PriceLevel = "retail" | "wholesale";

/** A quantity break: at `min_qty` or more, each unit costs `price`. */
export interface PriceTier {
  min_qty: number;
  price: number;
}

/** What the till knows about an item, from the catalog projection. */
export interface PricedItem {
  /**
   * Which product and which category this is.
   *
   * Needed only by the promotion rules, which scope by one or the other, so
   * both are optional — a caller pricing a cart with no promotions in play
   * never has to supply them, and a promotion simply does not match a line
   * that cannot say what it is.
   */
  id?: string;
  category_id?: string | null;
  price: number;
  discount_price: number | null;
  wholesale_price: number | null;
  price_tiers: PriceTier[] | null;
  tax_rate: number | null;
  /** The rate of the item's tax group, when it has one. Beats `tax_rate`. */
  tax_group_rate?: number | null;
}

/** One line in the cart. */
export interface CartLine {
  item: PricedItem;
  quantity: number;
  priceLevel?: PriceLevel;
  /** Sum of the chosen modifiers' price deltas, per unit. */
  modifierDelta?: number;
  /** A percentage off this line. Wins over `lineDiscount` when both are given. */
  lineDiscountPct?: number | null;
  /** A flat amount off this line, clamped so a line can never go negative. */
  lineDiscount?: number | null;
  /**
   * The MONEY this line named, where it named money instead of a quantity.
   *
   * "Do hazaar ka daal do." When it is set, `quantity` is the DERIVED figure
   * and this is the gross — not `unit × quantity` recomputed from it. Rs 2,000
   * at 268.50/L is 7.449 litres, and 7.449 × 268.50 is Rs 2,000.06.
   *
   * Six paisa is not a rounding preference here. The server refuses the sale
   * outright when the gross is recomputed — the tender no longer covers the
   * bill — so a till that priced it the other way would queue a sale that
   * cannot sync. Mirrored, not approximated.
   */
  amountAsked?: number | null;
}

export interface ShopPricing {
  /** Applied when an item carries no rate of its own. */
  default_tax_rate: number;
  /** True when prices already contain the tax rather than having it added. */
  tax_inclusive: boolean;
  /** Every automatic promotion this till holds, live or not. */
  promotions?: CatalogPromotion[];
  /**
   * SERVER time, with the till's measured drift already applied.
   *
   * Never `new Date()`. A tablet three days slow would run a flash sale that
   * ended on Tuesday, and the whole point of a mirror is that it cannot
   * disagree with the server about anything, least of all what day it is.
   */
  now?: Date;
  /** The shop's timezone, which is what a promotion's window is written in. */
  timezone?: string;
}

export interface PricedLine {
  unit_price: number;
  line_total: number;
  tax_rate: number;
}

export interface PricedCart {
  lines: PricedLine[];
  subtotal: number;
  /** Everything off the bill: what the cashier keyed, plus any promotion. */
  discount: number;
  tax: number;
  total: number;
  /** The automatic promotion that applied, when one did. */
  promotion: PromoResult | null;
}

/**
 * The price a buyer actually pays before quantity is considered.
 *
 * A sale price only counts when it is BELOW the regular one — a
 * `discount_price` above `price` is stale data, not a surcharge.
 */
function sellingPrice(item: PricedItem): number {
  const sale = item.discount_price;

  return sale !== null && sale > 0 && sale < item.price ? sale : item.price;
}

/**
 * The cheapest tier this quantity qualifies for, or the selling price.
 *
 * The CHEAPEST rather than the deepest `min_qty`: validation keeps tiers
 * monotonic, but should a non-monotonic set exist (legacy data, a deeper tier
 * priced higher) the buyer must still not be overcharged past a shallower,
 * cheaper break. And the result can never exceed the selling price, so a bulk
 * tier cannot override a deeper flash sale into an overcharge.
 */
function priceForQty(item: PricedItem, qty: number): number {
  let best: number | null = null;

  for (const tier of item.price_tiers ?? []) {
    const min = Number(tier.min_qty ?? 0);
    const price = Number(tier.price ?? 0);
    if (min > 0 && price > 0 && qty >= min && (best === null || price < best)) {
      best = price;
    }
  }

  const selling = sellingPrice(item);

  return best !== null ? Math.min(best, selling) : selling;
}

/**
 * Per-unit price for a chosen price level.
 *
 * Wholesale is a flat price LIST, so quantity tiers do not stack on top of it —
 * and it can never exceed retail, because a "wholesale" price above the shelf
 * price is a data-entry mistake and the customer should not pay for it.
 */
function priceForLevel(item: PricedItem, level: PriceLevel, qty: number): number {
  if (level === "wholesale" && item.wholesale_price !== null && item.wholesale_price > 0) {
    return Math.min(item.wholesale_price, priceForQty(item, qty));
  }

  return priceForQty(item, qty);
}

/** A tax group's rate beats the item's own; the shop default is the fallback. */
function effectiveTaxRate(item: PricedItem, shopDefault: number): number {
  if (item.tax_group_rate !== null && item.tax_group_rate !== undefined) {
    return item.tax_group_rate;
  }

  return item.tax_rate !== null ? item.tax_rate : shopDefault;
}

/**
 * Price a whole cart.
 *
 * `discount` is the whole-cart amount a cashier keyed in. It is applied after
 * the lines and before the tax, exactly as the server does, because tax is
 * charged on what is actually being paid.
 */
export function priceCart(lines: CartLine[], shop: ShopPricing, discount = 0): PricedCart {
  const priced: PricedLine[] = [];
  let subtotal = 0;

  for (const line of lines) {
    const level = line.priceLevel ?? "retail";
    const base = priceForLevel(line.item, level, line.quantity);

    // Same order as the server: round the unit price, THEN multiply — except
    // where the line named money, in which case the money IS the gross.
    const unitPrice = round2(base + (line.modifierDelta ?? 0));
    const gross = line.amountAsked != null
      ? round2(line.amountAsked)
      : round2(unitPrice * line.quantity);

    // A percentage wins if given; a flat amount is clamped to the line, so a
    // line can never go negative and drag the cart down with it.
    let lineDiscount = 0;
    const pct = line.lineDiscountPct ?? 0;
    const amt = line.lineDiscount ?? 0;
    if (pct > 0) {
      lineDiscount = round2((gross * Math.min(pct, 100)) / 100);
    } else if (amt > 0) {
      lineDiscount = Math.min(round2(amt), gross);
    }

    const lineTotal = round2(gross - lineDiscount);
    // Rounded at every addition, like the server. Summing raw and rounding once
    // drifts on a long cart.
    subtotal = round2(subtotal + lineTotal);

    priced.push({
      unit_price: unitPrice,
      line_total: lineTotal,
      tax_rate: effectiveTaxRate(line.item, shop.default_tax_rate),
    });
  }

  const keyed = round2(Math.min(round2(discount), subtotal));

  // ── The automatic promotion ─────────────────────────────────────────
  //
  // Exactly where the server applies it, and clamped exactly as the server
  // clamps it: never more than what is still owed after the cashier's own
  // discount. Applied AFTER the keyed discount and BEFORE tax, because tax is
  // charged on what is actually being paid.
  const promotion = bestPromotion(
    shop.promotions ?? [],
    priced.map((line, i) => ({
      productId: lines[i].item.id ?? "",
      categoryId: lines[i].item.category_id ?? null,
      quantity: lines[i].quantity,
      lineTotal: line.line_total,
    })),
    subtotal,
    shop.now ?? new Date(),
    shop.timezone ?? "Asia/Karachi",
  );

  const promoDiscount = promotion === null
    ? 0
    : round2(Math.min(promotion.discount, round2(subtotal - keyed)));

  const cartDiscount = promoDiscount > 0 ? round2(keyed + promoDiscount) : keyed;
  const taxableBase = subtotal - cartDiscount;

  let tax = 0;
  for (const line of priced) {
    const rate = line.tax_rate;
    if (rate <= 0 || subtotal <= 0) continue;

    // Each line's share of what is actually being paid, so a cart discount
    // reduces the tax proportionally rather than coming off one line.
    const share = line.line_total * (taxableBase / subtotal);

    if (shop.tax_inclusive) {
      // The price already holds the tax; take out the portion within it.
      const net = share / (1 + rate / 100);
      tax = round2(tax + (share - net));
    } else {
      tax = round2(tax + (share * rate) / 100);
    }
  }

  // Inclusive: the tax is already in the price and is not added again.
  const total = shop.tax_inclusive
    ? round2(subtotal - cartDiscount)
    : round2(subtotal - cartDiscount + tax);

  return {
    lines: priced,
    subtotal,
    discount: cartDiscount,
    tax,
    total,
    promotion: promoDiscount > 0 ? promotion : null,
  };
}
