import type { QaSection } from "./types";
import { PRODUCT } from "../../common/brand";

/**
 * WHAT THIS PRODUCT IS — read this before opening anything.
 *
 * Kept as prose rather than as a step, because a tester who starts clicking
 * without it will spend the first day reporting the rules as bugs.
 */
export const QA_INTRO = {
  title: "What you are testing",
  lines: [
    `${PRODUCT.name} is one system that runs a whole shop: the counter, the stock, the money and, if the shop wants one, its page on the internet. It is multi-tenant — every business has its own data, its own staff and its own settings, and they can never see each other's.`,
    "It is not written for one kind of shop. The SAME code runs a kiryana store, a chemist, a restaurant, a workshop, a filling station, a salon and a books-only office, and each of them sees a different product. That is the single most important thing to hold on to while testing: a screen that is missing is usually missing on purpose.",
  ],
  axes: [
    {
      name: "MODULE",
      text: "What this shop was GIVEN. Set by the platform admin when the business is created. Twenty of them — the till, stock, suppliers, disposals, the kitchen pass, online store, and so on. Settings → Your modules shows the shop its own list.",
    },
    {
      name: "TRADE",
      text: "What KIND of business it is (food, mart, pharmacy, retail, services, automotive, petroleum, finance). It decides vocabulary, item types and a handful of trade-only screens — a chemist gets a dispensing register, a workshop gets a bay board.",
    },
    {
      name: "PERMISSION",
      text: "What THIS PERSON may do. There are no job roles: a cashier is a set of permissions, and an owner holds all of them. A cashier is not shown Reports and cannot open them by typing the URL either.",
    },
  ],
  before: [
    "Before reporting anything missing, check all three. Most first-week bug reports are one of them doing its job.",
    "Money is always PKR and prices always come from the SERVER — the till sends what was scanned and how many, never a price. A price you can change in the browser and have accepted is a serious bug; a price you cannot change is the design.",
    "A trading day that has been closed is never rewritten, not even by a sale that arrives late. Figures moving on a closed day is a serious bug; being told about a shortfall instead is the design.",
  ],
};

export const QA_SECTIONS: QaSection[] = [
  {
    id: "start",
    title: "Getting in",
    blurb: "Who you are signed in as decides most of what you will see, so establish that first.",
    steps: [
      {
        id: "sign-in",
        title: "Sign in, and know which shop you are in",
        summary: "Everything below depends on the shop and the person. Pin both down before you click anything else.",
        screen: "/signin",
        required: "always",
        what: [
          "One login serves three different products: the shop panel (a shopkeeper), the marketplace (a customer buying something), and the admin console (the platform operator). The role on the account decides which one you land in.",
          "A shop's name, logo and colours are its own. If the panel looks like a different business than the one you signed into, stop — that is a tenancy bug and it is the most serious kind there is.",
        ],
        checks: [
          { do: "Sign in as the shop owner of the shop you are testing.", expect: "You land on that shop's dashboard, with that shop's name in the header." },
          { do: "Read the shop name and, if the shop has more than one branch, the branch shown in the header.", expect: "Both match the shop you meant to sign into. Write them down — every figure you check later belongs to this shop and this branch." },
          { do: "Sign out and sign in as a cashier of the same shop (ask for one, or make one under Staff).", expect: "A much shorter menu. This is the PERMISSION axis and you will use it repeatedly." },
        ],
        wrong: [
          "Any data from another shop, anywhere, ever. One shop's product, customer, sale or figure appearing in another is the highest-severity bug in this product.",
          "A screen a cashier is offered in the menu and then refused when they open it. The menu and the door must agree.",
        ],
      },
      {
        id: "shape",
        title: "The shape of the panel",
        summary: "A rail on the left, a header, and the screen. Two menu depths, and a reason for both.",
        required: "always",
        what: [
          "The sidebar has a Simple view (the five or six screens a shop uses daily) and a Full view (everything it has). New shops start Simple so they are not handed forty links on day one.",
          "On a tablet the rail collapses to icons. That is why two screens must never wear the same icon — at that width the picture is the only label.",
        ],
        checks: [
          { do: "Switch between Simple and Full.", expect: "Full never HIDES something Simple shows. Simple is a smaller menu, not a different business." },
          { do: "Collapse the sidebar to icons.", expect: "No two visible icons are identical." },
          { do: "Open the panel on a phone-sized window (about 390 points wide).", expect: "The rail becomes a drawer, and no screen scrolls sideways. Sideways scroll on any screen is a bug — the page body must never move horizontally." },
          { do: "Narrow the window to 320 points — the smallest phone still in use.", expect: "The header keeps the menu button, the mark, search, the branch (on a shop with more than one), the bell and the account button, and drops the product's NAME. Nothing runs past the right edge and the page cannot be dragged sideways." },
          { do: "On a laptop, read the search field in the header, then click it.", expect: "It says what it finds and that it jumps to a screen, and shows Ctrl K on a PC (⌘ K on a Mac). Opened with nothing typed it lists screens to go to — it does not tell you to type two characters." },
          { do: "Type exp in search and press Enter.", expect: "Expenses is offered first, under Screens, and Enter opens it. The count at the foot is not 0." },
          { do: "On a shop with two or more branches, open the branch control with the keyboard (focus it, Down arrow), move with the arrows and press Enter on a branch.", expect: "The control turns the shop's colour and names that branch; the dashboard's figures are that branch's. Choose All branches: it goes back to plain. The default branch is tagged Default or Main branch — never \"Main — Main\"." },
          { do: "On a phone, tap the magnifying glass, then the branch control.", expect: "Both are there, and both open inside the screen. With one branch chosen the control is coloured even though there is no room for the name." },
          { do: "Open any list — Customers, Suppliers, Sales, Purchases — with the network cut (DevTools → Network → Offline) and reload.", expect: "After a few seconds the list says it could not be loaded, with a Try again button. It does NOT say \"No customers yet\" — a list that did not arrive is not an empty list — and it does not say \"Counting…\". Put the network back and press Try again: the list is there." },
          { do: "Sign in as staff with no permission for a list, and open it by its address.", expect: "It says you do not have access to that list — not that the list is empty, and not that it failed." },
          { do: "With a screen reader (or the browser's accessibility tree), jump to the first heading on any screen.", expect: "There is exactly one, and it is the screen's own name — Customers, Sales, Expenses. The till has one that is read aloud and not drawn. The item form is a dialog over Products and is announced by its own title." },
          { do: "Sign in to a business that only keeps books (Expense Manager and nothing else) and open Subscription.", expect: "The plan is named with its price and how far back it keeps the books. It does NOT say \"One shop, one counter. Everything a single till needs\" — that is the plan's description for a shop. Sign in to a shop on the same plan: the sentence is there in full." },
        ],
      },
    ],
  },

  {
    id: "modules",
    title: "What this shop has",
    blurb: "The single biggest source of false bug reports. Learn it before anything else.",
    steps: [
      {
        id: "your-modules",
        title: "Your modules",
        summary: "The shop's own list of what it was given — and what it was not.",
        screen: "/tenant/settings",
        required: "always",
        what: [
          "Settings → Your modules lists all twenty-one modules with a tick or a dash. It is read-only for the shop: modules are the platform admin's decision, because a shop able to switch its own till off would be a support call.",
          "This is the answer to 'why can I not see Purchases'. Open it FIRST whenever a screen you expected is not there.",
          "Modules depend on each other. Suppliers & Purchases needs Inventory, which needs Products. A module standing on one that is off is not enabled, however the list was written.",
        ],
        checks: [
          { do: "Open Settings → Your modules and write down which are on.", expect: "The count at the top matches the ticks. Everything OFF is listed too, with its description." },
          { do: "Compare the list with the sidebar.", expect: "Every module that is ON has its screens in the menu, and no module that is OFF does." },
          { do: "Type the URL of a screen whose module is off — for example /tenant/disposals with Disposals off.", expect: "You are refused, not shown an empty page. A screen hidden from the menu but reachable by URL is a real bug." },
        ],
        wrong: [
          "A screen offered in the menu that answers 'this module is not enabled for your shop' when opened. The menu, the route and the server must agree — all three or none.",
        ],
      },
      {
        id: "admin-modules",
        title: "Turning modules on and off (admin side)",
        summary: "How a shop gets what it has. You will use this constantly to set up test cases.",
        screen: "/admin/tenants",
        required: "always",
        what: [
          "Sign in as the platform admin, open a tenant, and there is a Modules card in three bands: IN ITS PLAN (what the plan gives a shop of that trade), ADD-ONS (the rest of what the trade can use, each with its price), and a folded 'Not usual for this trade'.",
          "An add-on is switched on for ONE shop. The shop stays on its plan — nobody makes a custom plan for one extra module — and the add-on's monthly price is added to that shop's bill for as long as it is on. The 'What it pays' card beside Actions shows the sum.",
          "Switching one ON pulls up everything it stands on and says what else it moved. Switching one OFF drops everything built on it, and says that too.",
          "The same picker appears when a business is created: choose the trade and the plan, and what that plan gives that trade is switched on. A mart is not shown a kitchen pass; a restaurant on Basic still gets one.",
          "What each plan includes is ticked on Plans (Edit → Modules), and what each add-on costs is set at the foot of that page.",
          "A plan's price is the figure TYPED on the plan. It is never added up from the add-on prices, and changing an add-on price never moves a plan's price. What a shop pays is its plan's price plus the add-ons that shop has.",
          "So an add-on price only ever reaches a shop that has that module PAST its plan. Under every price on that list is a line saying where it can be charged, and it is one of three: which plans leave the module out and how many shops have it as an add-on today; or that every plan includes it and no shop has it as an add-on, so the price is charged to nobody; or that every plan on offer includes it and a shop has it as an add-on all the same — its trade does not usually take it, or its plan is no longer offered — and the price is on THAT shop's bill.",
          "The third is the one to watch. A books-only business given Products is billed the Products price although Products is in every plan, because no plan includes it for a business that only keeps books. A line turns amber when a price is typed where it reaches nobody, or reaches a shop like that.",
        ],
        checks: [
          { do: "Switch Suppliers & Purchases ON for a shop that has nothing.", expect: "Inventory and Products come on with it, and the row says 'Also switched on: Products, Inventory'." },
          { do: "Switch Inventory OFF again.", expect: "Suppliers & Purchases, Stocktake and Disposals go with it, and the row names them." },
          { do: "Save, then look at the shop side.", expect: "The sidebar matches immediately. No screen survives whose module you just removed." },
          { do: "Price Customers & Khata at Rs 500 on Plans, then switch it on for a shop on Basic.", expect: "The shop is still on Basic. Its 'What it pays' card gains an Add-on line and reads Rs 2,999. Switch it off and it reads Rs 2,499 again." },
          { do: "Edit Basic on Plans and tick another module.", expect: "Shops already on Basic do not change — only what a NEW shop starts with, and which of a shop's modules are called add-ons." },
          { do: "On Plans, read the line under a module Basic leaves out, then under one every plan includes.", expect: "The first names the plans it is an add-on on and counts the shops that have it now. The second says a price there is charged to nobody — but ONLY if no shop has it past its plan; otherwise it names the shop (or counts them, past three) and says the price goes on its bill." },
          { do: "Switch Fuel Management on for a mart, then read the line under Fuel Management on Plans.", expect: "It is in every plan on offer, yet that mart has it as an add-on. Type a price there: the line turns amber as you type, and once saved the mart's 'What it pays' has grown by exactly that. It never says the price is charged to nobody." },
          { do: "Type a price beside a module the line says is charged to nobody.", expect: "The line turns amber as you type. Saved, no shop's bill and no plan's price has moved." },
          { do: "Open Plans in two browser windows. In the first, price one module and save. In the second — do not reload it — price a DIFFERENT module and save.", expect: "Both prices are on the list. The second window's save did not take the first one's price off: a save says only the boxes that were typed in. Save is disabled until something is typed." },
          { do: "Clear one priced box and save.", expect: "That module is free to add again. Every other price is exactly as it was." },
          { do: "Type a price for a module Basic leaves out, save, and open a Basic shop that has it.", expect: "Its 'What it pays' card grew by exactly that. Basic's own price on the plan card did not move." },
        ],
        wrong: [
          "A save that appears to work and changes nothing. Every save in this product must either succeed visibly or say why it did not — a silent failure is a bug in itself.",
        ],
      },
    ],
  },

  {
    id: "catalog",
    title: "The catalog",
    blurb: "Nothing can be sold, counted or reported on until it exists here, so this is where a shop starts.",
    steps: [
      {
        id: "categories",
        title: "Categories",
        summary: "How the till groups things. Do this before products, or you will be typing them twice.",
        screen: "/tenant/categories",
        module: "products",
        required: "module",
        what: [
          "Categories are what the till's tiles are grouped by and what most reports break down by. A shop's trade proposes a starting set when it is created — a chemist gets Tablets and Syrups, a restaurant gets Starters and Main Course.",
          "They can be reordered by dragging, and hidden without being deleted. Hiding is not deleting: a hidden category's products keep their history.",
        ],
        checks: [
          { do: "Add a category, rename it, hide it, and drag it to a new position.", expect: "Each of the four saves and survives a page reload. A rename that snaps back is a save that failed silently — report it." },
          { do: "Hide a category that has products in it.", expect: "The products are still sellable and still in reports. Hiding groups things on a screen; it does not withdraw stock." },
        ],
      },
      {
        id: "products",
        title: "Products and services",
        summary: "The biggest screen in the product, and the one everything else reads from.",
        screen: "/tenant/products",
        module: "products",
        what: [
          "One record per thing the shop sells. What KIND of thing it may be depends on the trade: a restaurant writes dishes, a chemist dispenses medicine, a mart stocks packaged goods, a salon bills labour. A shop is only offered the item types its trade and its modules allow.",
          "A product carries a selling price and a COST. The cost is what every margin figure in the product is worked out from, and it is re-blended automatically when stock is received at a new price — so it is not a field a shop has to maintain by hand.",
          "Sizes (variants) are a real thing here, not a label: a large pizza and a small one have their own price, their own stock and their own barcode. So does a pack of twelve against a single.",
        ],
        required: "module",
        checks: [
          { do: "Add a plain product with a name, a price and a cost.", expect: "It appears in the list and, if the shop has a till, on the till within a few seconds." },
          { do: "Add a product with two sizes at different prices.", expect: "The till asks WHICH size when you tap it, and refuses to sell the parent on its own. Selling a sized product without choosing a size would be a bug." },
          { do: "Give one size its own barcode and scan it.", expect: "That size lands in the cart — not the other one, and not the parent." },
          { do: "Add a pack (Carton = 24) with its own price and barcode, then press \u201c+ Add a code\u201d on it and type a second barcode. Save, and scan the SECOND code at the till.", expect: "A Carton lands on the bill at the carton's price. One piece at the piece's price is the bug: a carton would leave for the price of one." },
          { do: "Note the pack's id (Network tab), change only the item's description, save, and look again.", expect: "The same id. A pack that gets a new id on every save breaks whatever was holding the old one — a till's bill, an offline tablet, a quotation." },
          { do: "Type the item's own barcode as one of its carton's codes. Then try a code that is already on another item.", expect: "Both refused, in words that say why, and nothing saved. A code means one thing." },
          { do: "Delete the item and add it again with exactly the same codes.", expect: "It saves. A deleted item's codes used to stay taken for ever." },
          { do: "Try to save a product with no name.", expect: "The field is named in an error next to it. A save that fails with nothing on screen is one of the defects this product has had before and must not have again." },
          { do: "Mark a product sold out (86) from the list.", expect: "It is refused at the TILL, on the dine-in tab and in an online order — all three. One of them still selling it is a bug." },
        ],
        wrong: [
          "A price the browser can change. Open the network tab, edit the price in the request, and send it: the sale must be priced by the server anyway.",
          "A code printed on a pack ringing a single piece — online or with the internet off.",
        ],
      },
      {
        id: "labels",
        title: "Barcode labels",
        summary: "Printing shelf labels from the catalog. Its own module — most small shops never switch it on.",
        screen: "/tenant/labels",
        module: "labels",
        required: "module",
        what: [
          "A label is printed from the catalog record, not from a shelf. The screen builds a sheet you can print — it does nothing to stock and nothing to prices.",
          "Optional on purpose: it is worth nothing without a label printer, so most shops start without it.",
        ],
        checks: [
          { do: "Select a few products and print to PDF.", expect: "The sheet carries the name, price and barcode of each, and the barcodes scan." },
          { do: "Ask for more labels than one sheet holds (73 on the standard sticker).", expect: "The page says 30 fit on a sheet and 3 sheets; the arrows page through all three; the PDF has three pages." },
          { do: "Change the sticker size and switch Price off in the drop-downs above the sheet, then reload.", expect: "It says Saved for your shop, the sheet follows at once, and both choices are still there after the reload. Settings \u2192 Barcodes no longer has those switches." },
          { do: "Give an item a pack with its own barcode and price.", expect: "The pack is its own row with its own count, and its sticker carries the pack's barcode and the pack's price." },
        ],
      },
    ],
  },

  {
    id: "stock",
    title: "Stock",
    blurb: "What is on the shelf, what it cost, and what happened to what is no longer there.",
    steps: [
      {
        id: "inventory",
        title: "Stock levels and adjustments",
        summary: "What the shop believes it holds, and the only honest way to change it by hand.",
        screen: "/tenant/inventory",
        module: "inventory",
        required: "module",
        what: [
          "Stock is held PER BRANCH. A shop with two shops has two numbers for the same product, and the till sells from the branch it is standing in.",
          "An adjustment is a correction with a reason attached. It is not how goods normally arrive — that is a purchase — and a shop using adjustments to receive stock will have meaningless cost figures.",
          "A product can be marked not-tracked, and then it has no stock number at all. A service always is.",
        ],
        checks: [
          { do: "Adjust a product up by 10 with a reason.", expect: "The number moves by exactly 10, on the branch you are in, and the movement is listed with your name against it." },
          { do: "Adjust a SIZED product from the parent row.", expect: "You are asked which size, or told to pick one. A parent adjustment that reports success and moves nothing is a bug this product has had." },
          { do: "Switch to another branch and read the same product.", expect: "A different number. Stock in one branch must never move because you sold from another." },
        ],
      },
      {
        id: "purchasing",
        title: "Suppliers and purchases",
        summary: "How goods actually arrive, and how cost stays honest.",
        screen: "/tenant/purchases",
        module: "purchasing",
        required: "module",
        what: [
          "A supplier is a vendor with a running balance — what the shop owes them. A purchase order is what was ordered; RECEIVING it is what moves stock and what the shop then owes.",
          "Receiving at a new price re-blends the product's cost (a weighted average per base unit). That is why margins can be trusted without anybody maintaining a cost field.",
          "Raising an order and receiving one are different jobs and different permissions: the buyer orders, the stock keeper checks the goods off the bay.",
        ],
        checks: [
          { do: "Create a supplier, raise a PO for 10 of something at a price different from its current cost, and receive it.", expect: "Stock rises by 10, the product's cost moves to a blend of old and new, and the supplier's balance rises by the order value." },
          { do: "Pay the supplier from their own card.", expect: "The balance falls by what you paid. A Pay button that answers success and moves nothing is a defect this product has had — check the balance, not the message." },
          { do: "Receive only part of an order.", expect: "Stock rises by what arrived, and the order still shows what is outstanding." },
        ],
      },
      {
        id: "stocktake-disposals",
        title: "Stocktake and disposals",
        summary: "Counting the shelf, and recording what left without being sold.",
        screen: "/tenant/stocktake",
        module: "stocktake",
        required: "module",
        what: [
          "A stocktake is a counting sheet: you enter what is actually on the shelf and APPLYING it writes the difference off. Applying is manager-only, because it moves stock against the shop's own books.",
          "A disposal is stock that left without being sold — expired, damaged, or returned to the supplier. Written-off and returned-to-supplier are never added together: one is a loss and the other is a claim.",
        ],
        checks: [
          { do: "Draw a sheet, enter a count lower than the system's, and apply it.", expect: "Stock becomes what you counted, and the difference is recorded as a variance you can find later." },
          { do: "Dispose of a batch as expired, and another as returned to the supplier.", expect: "They appear under different headings, and only the returned one produces a claim against the distributor." },
        ],
      },
    ],
  },

  {
    id: "till",
    title: "The till",
    blurb: "Where the shop's money is actually taken. More of this product runs through here than through everything else put together.",
    steps: [
      {
        id: "pos-basics",
        title: "Ringing a sale",
        summary: "Find the thing, put it in the basket, take the money, hand over a receipt.",
        screen: "/tenant/pos",
        module: "pos",
        required: "module",
        what: [
          "The till runs FULL SCREEN with no sidebar, because a counter is not a place to browse a menu. There is exactly one way out and it is marked Exit.",
          "Three ways to find something: scan a barcode, search by name, or tap a tile. A food shop gets picture tiles by default and a mart gets a dense list of rows, because one has forty dishes and the other has four thousand SKUs. The tester can switch the view and it is remembered per device.",
          "The cart is priced by the SERVER. What the browser sends is the product and the quantity.",
        ],
        checks: [
          { do: "Scan or search an item and add it. Change the quantity. Remove it.", expect: "The running total is right after each action, and every line is visible — a cart that hides its own lines below the fold is a defect this product has had." },
          { do: "Add a weighed item (per kg) and enter 1.25.", expect: "It prices at 1.25 × the kilo price, and the receipt says the weight." },
          { do: "Take cash for more than the total.", expect: "The change is worked out and shown large. Cash rounding, if the shop set any, is applied and stated." },
          { do: "Complete the sale.", expect: "A receipt number, a printable receipt, and the cart cleared ready for the next customer." },
        ],
        wrong: [
          "\u201cNo products match.\u201d on a till whose product list failed to load. A failed list says it could not be loaded and offers Try again; only a search that found nothing says nothing matches.",
          "Any price the browser can dictate.",
          "A tender screen that lets you complete a sale for less than the total without it being a credit (khata) sale.",
        ],
      },
      {
        id: "pos-options",
        title: "Everything else the till can do",
        summary: "Discounts, customers, held tickets, split payment, credit — the options a real counter needs.",
        screen: "/tenant/pos",
        module: "pos",
        required: "module",
        what: [
          "A discount can be a value or a percent, and the shop can set a CEILING on it. The ceiling is checked on the server for every door a sale comes in by, not just the till.",
          "Attaching a customer is how khata (credit), loyalty points and a group's price level reach the sale. The till finds a customer by PHONE — a customer with no phone cannot be found at the counter, which is why a credit limit without a phone is refused.",
          "Holding a ticket parks a basket so the next customer can be served. Online it is shared across every lane and resumed by a locked claim so two lanes cannot ring the same basket. With no line it is parked on THAT TILL and the screen says so.",
          "Tenders: cash, card (recorded, there is no gateway anywhere in this product), split across both, and credit (khata) which needs a customer.",
        ],
        checks: [
          { do: "Apply a discount larger than the shop's ceiling.", expect: "Refused, with the ceiling named. Try the same through a quote and an online order — refused there too." },
          { do: "Attach a customer by phone, then sell on credit.", expect: "The customer's balance rises by exactly the credit part, and the sale cannot give cash change." },
          { do: "Hold a ticket with a name, serve someone else, then resume it.", expect: "The basket comes back exactly as it was — items, discount, customer, table." },
          { do: "Split a bill across cash and card.", expect: "The two must add up to the total, and both appear on the receipt and in the day's tender breakdown." },
        ],
      },
      {
        id: "shift",
        title: "The drawer and shifts",
        summary: "The cash box, who is standing at it, and whether it balances at the end.",
        screen: "/tenant/pos",
        module: "pos",
        required: "module",
        what: [
          "A shift is opened with a float — the change the cashier starts with. Every cash sale, payout, drop and refund on that till belongs to that shift.",
          "Money moves in and out for reasons that are not sales: paid in, paid out, a drop to the safe. Each needs a reason, and each is on the Z-read.",
          "Closing counts the drawer, note by note if the shop wants, and compares it with what the shop's own books say should be there. The difference is the VARIANCE, and it is the number the whole feature exists to produce.",
          "A blind close hides the expected figure until after the count, so the cashier cannot count backwards from it.",
          "Training mode is a practice till: the shift is the unit, so a whole shift is practice. Practice sales take nothing off the shelf and appear in no figure.",
        ],
        checks: [
          { do: "Open a shift with a float of 3,000. Ring a cash sale of 500. Pay out 200 with a reason.", expect: "The X-read shows float 3,000, cash sales 500, paid out 200, expected 3,300." },
          { do: "Close it and count exactly 3,300.", expect: "Variance zero. Count 3,200 instead and the variance is −100, and it is recorded, not hidden." },
          { do: "Open a shift, then try to open a second on the same lane as another cashier.", expect: "Refused — one open shift per lane and one per cashier." },
          { do: "Open a PRACTICE shift and sell.", expect: "Stock does not move, the sale is numbered separately, and it appears in no report or drawer figure." },
        ],
        wrong: [
          "A close that reports a variance the shop cannot reproduce from its own numbers. Every figure in a Z-read must be re-derivable from the sales and movements listed under it.",
        ],
      },
      {
        id: "day",
        title: "The trading day and banking",
        summary: "What the whole shop took today across every drawer, and how much of it went to the bank.",
        screen: "/tenant/day",
        module: "pos",
        required: "module",
        what: [
          "A shift is one cashier's drawer; a DAY is the shop. A day can hold several shifts and several lanes, and it is what gets closed off and banked.",
          "A deposit is money leaving the shop for the bank. It is recorded against the day.",
          "Once a day is closed its figures never change again — not for a correction, and not for a sale that was stuck on an offline till and arrives on Friday. That is deliberate: a variance somebody counted and accepted has to still mean the same thing in six months.",
        ],
        checks: [
          { do: "Close two shifts, then close the day.", expect: "The day's takings equal the shifts' takings, and the day is marked closed by you with a time." },
          { do: "Record a bank deposit.", expect: "It appears against the right day, and the shop can see what is still in the shop against what went to the bank." },
          { do: "Ring a sale dated into a closed day (or let an offline sale arrive after a close).", expect: "The closed day does NOT move. The shortfall is named in rupees on Reports → Offline instead. Figures changing on a closed day is a serious bug." },
          { do: "Close off today's day in the afternoon, then try to open a shift at the till.", expect: "Refused, and the message says a manager can open the day again from Day & banking. The Day screen names the closed day — date, time, who — instead of \"No day open yet\"." },
          { do: "On that screen press Open today again, give a reason, then open a shift and sell.", expect: "The shift opens in the SAME day. The day says it was closed off earlier and opened again, with your reason. Closed off properly tonight, its total is BOTH parts of the day. Activity has one line: who, why, and what it had been closed at." },
          { do: "As a cashier (no reports permission), open Day & banking after a close.", expect: "The closed day is named, with no Open again button — it says to ask a manager. A button that is drawn and then refuses is a bug." },
          { do: "Tomorrow, try to open yesterday's closed day again (there is no button; call it if you can).", expect: "Refused: only today can be opened again. Yesterday reads exactly as it was signed." },
          { do: "After midnight, with last night's day still OPEN, open a new shift.", expect: "It joins last night's day — one day, not two. The dashboard does not say yesterday was never closed until five in the morning has passed." },
          { do: "Close the day at 11:50 pm, then open a shift at 12:30 am and sell.", expect: "A NEW day starts, dated by the calendar. The closed day does not move, and the dashboard shows a day open." },
          { do: "At 1 am, with sales rung at 10 pm and at 12:30 am, read the dashboard, Reports → daily, the cashbook, the ledger and the sales list on Today.", expect: "All five show BOTH sales, under yesterday's date. After 5 am all five show none for the new day. Any screen that disagrees with the others is a bug." },
          { do: "Settings → Tax & Delivery → Your trading day: choose Midnight, save, and repeat the 1 am check.", expect: "Every one of those screens now puts the 10 pm sale on yesterday and the 12:30 am sale on today. A screen that did not move is a bug. Put it back to The usual afterwards." },
        ],
        wrong: [
          "Two trading days open at one counter because a shift was opened after midnight.",
          "\"Today\" on a list showing nothing while the dashboard is still counting the same evening.",
        ],
      },
    ],
  },

  {
    id: "customers",
    title: "Customers, khata and offers",
    blurb: "Who owes the shop money, and what the shop takes off a bill.",
    steps: [
      {
        id: "khata",
        title: "Customers and credit",
        summary: "The customer book. In this market it is mostly about who owes what.",
        screen: "/tenant/customers",
        module: "customers",
        required: "module",
        what: [
          "A customer is found at the till BY PHONE and by nothing else. A customer without a phone can be recorded but can never be attached to a sale — which is why a credit limit on a customer with no phone is refused when it is set, rather than discovered at the counter.",
          "A credit (khata) sale puts the amount on the customer's balance. A repayment brings it down. The statement is the running list, and the balance must be re-derivable from it.",
          "Loyalty points, where the shop runs them, are earned on a sale and redeemed at the till.",
        ],
        checks: [
          { do: "Add a customer with a phone and a credit limit. Sell to them on credit up to the limit, then past it.", expect: "The first goes through, the second is refused with the limit named." },
          { do: "Record a repayment.", expect: "The balance falls by exactly that, on the customer card, in the customer list and in the statement — all three, and they must agree." },
          { do: "Try to give a credit limit to a customer with no phone.", expect: "Refused, and told why. Accepting it would create a khata nobody can ever use." },
        ],
      },
      {
        id: "offers",
        title: "Coupons, promotions and bank offers",
        summary: "Three different ways money comes off a bill, and three different people who set them up.",
        screen: "/tenant/coupons",
        module: "promotions",
        required: "module",
        what: [
          "A COUPON is a code the customer hands over. A PROMOTION applies itself when the basket qualifies — buy one get one, a percentage off a category, a happy hour. A BANK OFFER is a discount the BANK funds on its own cards, and it is its own module because almost nobody outside a mid-sized retailer runs one.",
          "All three are checked by the server as the sale is rung, so nobody at a counter can make an expired offer work.",
        ],
        checks: [
          { do: "Make a coupon, use it, and use it again past its limit or its date.", expect: "Accepted the first time, refused after, with the reason." },
          { do: "Make a buy-one-get-one promotion and ring two of the item.", expect: "The discount applies itself with nothing typed, and the receipt says what came off." },
          { do: "Check a coupon at the till as a CASHIER.", expect: "Allowed. Creating one is marketing; checking the one in a customer's hand is the counter's job, and requiring the first to do the second was a real defect here." },
        ],
      },
    ],
  },

  {
    id: "doors",
    title: "The other ways a sale happens",
    blurb: "The counter is not the only door. Every one of these ends in the same Sale row and must move the same drawer.",
    steps: [
      {
        id: "sales-refunds",
        title: "Sales, refunds and exchanges",
        summary: "The record of everything sold, and the two ways money goes back.",
        screen: "/tenant/sales",
        module: "pos",
        required: "module",
        what: [
          "The sales list is every sale by every door. Search it by receipt number, by the customer's phone, or by the OFF- slip number a customer is holding from an offline sale.",
          "A refund gives money back and puts stock back. An EXCHANGE swaps goods and settles the difference — the two are different because one moves money out and the other may move it either way.",
          "A void (cancel) is not a refund: it unwinds a sale that should never have been rung.",
          "Revenue is reported GROSS with refunds as their own dated line. A refund is dated by the day it was handed back, because netting it into the original day would rewrite a day that has been closed and banked.",
        ],
        checks: [
          { do: "Refund one line of a two-line sale.", expect: "Money out matches that line, that line's stock comes back, and the sale is marked partially refunded — and it is STILL counted in the day's sales. A whole ticket vanishing from a report because one item came back is a defect this product has had." },
          { do: "Search for a sale by the customer's phone, then by an OFF- slip number.", expect: "Both find it." },
          { do: "Void a sale.", expect: "Stock returns, the drawer moves back, and the sale reads cancelled rather than disappearing." },
        ],
      },
      {
        id: "documents",
        title: "Quotes and advances",
        summary: "A price promised before there is a sale, and money taken before the goods go.",
        screen: "/tenant/documents",
        module: "documents",
        required: "module",
        what: [
          "A quotation is a price the shop has promised. An advance is money taken against goods not yet handed over. Both end at the counter: converting one produces a real sale and moves the drawer.",
          "Its own module because a counter that only rings and hands over has no use for either.",
        ],
        checks: [
          { do: "Write a quote, then convert it.", expect: "A sale is created for the quoted amount, and the DRAWER moves by it. A door that creates a sale without touching the drawer is a defect this product has had — check the drawer every time." },
          { do: "Take an advance, then complete the order later.", expect: "The advance is deducted from what is still owed, and both movements are on the day." },
        ],
      },
      {
        id: "kitchen",
        title: "Dine-in, the kitchen pass, and takeaway",
        summary: "How a food shop's order reaches the people who have to cook it.",
        screen: "/tenant/kitchen",
        module: "kitchen",
        trades: ["food"],
        required: "module",
        what: [
          "Two different modules, and this is worth understanding before testing either. The KITCHEN PASS is the screen on the kitchen wall — what to cook, oldest first, bumped when it is ready. DINE-IN is a floor of tables with running tabs, settle and split bills.",
          "A takeaway café needs the pass and no floor at all, which is why they are separate. Dine-in depends on the pass, because a Send-to-kitchen button whose ticket lands nowhere would be a floor with no kitchen.",
          "A takeaway rung at the TILL now reaches the pass by itself the moment it is paid. Only the things a kitchen makes are on the docket — a bottle off the chiller is not work for the pass.",
          "And it PRINTS. Half of \u201csent to the kitchen\u201d is the board; the other half is paper, which is how most small kitchens work. Settings \u2192 Point of Sale \u2192 Kitchen carries the stations and the print switch, and that tab follows the Kitchen module \u2014 a takeaway counter with no tables must be able to reach it.",
        ],
        checks: [
          { do: "With only the Kitchen module on, ring a takeaway with a dish and a bottle of water.", expect: "A docket appears on the pass carrying the DISH only, headed by the customer's name if one was typed, and carrying the sale's own receipt number." },
          { do: "Mark it served.", expect: "It leaves the board and closes itself. There is no bill left to settle — it was paid at the counter." },
          { do: "With Dine-in OFF, open Settings → Point of Sale.", expect: "A Kitchen tab is there, carrying the stations and \u201cPrint kitchen tickets\u201d. It used to appear only for shops with tables, which left a takeaway café unable to configure the one module it bought." },
          { do: "Leave that switch on and ring another takeaway.", expect: "The kitchen slip prints as well as landing on the board. If it cannot print, the till says so and names the board as the fallback — silence here means the kitchen was told nothing." },
          { do: "Switch Dine-in on as well. Open a tab on a table, add items, fire, settle.", expect: "The tab appears on the FLOOR; the takeaway orders do not. A paid counter order showing up on the floor as an open table would be a bug." },
          { do: "Cancel a tab that has fired dockets.", expect: "Its dockets leave the pass. A docket outliving its tab is a defect this product has had." },
          { do: "On a table's tab, tap one dish three times quickly.", expect: "ONE line that says 3, and the dish's tile shows a 3 in its corner. It used to be three lines of one — and three rows on the kitchen's ticket." },
          { do: "Use \u2212 and + on that line, then step a line of one down again.", expect: "The number and the price follow each press. At one, the minus becomes an \u00d7 and pressing it takes the line off the tab." },
          { do: "Press Kitchen note on an unsent line, choose \u201cNo chilli\u201d, save, then Send to kitchen.", expect: "The note shows on the line in red, and on the kitchen board's card in red capitals. After sending, the line has no \u2212 / + any more \u2014 only Void." },
          { do: "Look at the floor while that order is cooking, then mark it Ready on the kitchen board.", expect: "The table's tile says \u201cIn kitchen\u201d, then turns green and says \u201cFood ready\u201d within a few seconds, with the bill, the guests and how long they have sat." },
          { do: "Open a takeaway from the floor, give it a name, add a dish, and go back to the floor.", expect: "It has a tile of its own in a Takeaway row above the tables. It used to vanish the moment you stepped back." },
          { do: "On the kitchen board with tickets in all three columns, press each ticket's button.", expect: "New \u2192 Cooking \u2192 Ready \u2192 gone. The counts at the top follow. With a station chosen, Clear board names that station and how many tickets, and clears only those." },
          { do: "Leave a ticket unserved overnight (or use a shop that has old ones) and open the board next day.", expect: "Today's board does not show it. An amber strip counts what is left from before today; Show them lists exactly those, and Clear all takes them off after asking once. They are marked cleared, not served." },
          { do: "Leave a table's tab open overnight and open the floor next day.", expect: "A red strip counts it, its tile is tagged \u201cFrom earlier\u201d, and Close them (owner, or \u201cServe any table\u201d) closes every such tab in one press \u2014 except any with a payment already on it, which it says it kept." },
          { do: "Open the floor, a tab and the kitchen board on a tablet.", expect: "A strip of icons stays down the left on all three. Touching an icon with screens under it opens the menu over the page; touching anywhere else closes it. The till has no such strip." },
        ],
      },
      {
        id: "online",
        title: "Online orders, delivery and the storefront",
        summary: "The shop's page on the internet, and the orders that come from it.",
        screen: "/tenant/orders",
        module: "marketplace",
        required: "module",
        what: [
          "The marketplace is a shopper's view across shops. A customer builds a basket, checks out, and the shop sees an order. Delivery adds riders; a shop can take phone and WhatsApp orders through the same screen with no storefront at all.",
          "An order for a multi-branch shop is filled by the nearest branch that holds the WHOLE basket — not by splitting it.",
          "Where the MONEY was taken is not the same question as where the order came from. A pickup order collected at the counter moves the drawer; a delivery does not.",
        ],
        checks: [
          { do: "Place an order from the storefront as a customer, then accept it in the shop.", expect: "It appears with the right items and total, and the customer's own order screen follows its status." },
          { do: "Collect a pickup order at the counter.", expect: "The drawer moves. A delivery order settled elsewhere must NOT move it." },
          { do: "Order something the shop has none of.", expect: "Refused with the item named, not accepted and silently short." },
        ],
      },
    ],
  },

  {
    id: "money",
    title: "Money in and money out",
    blurb: "Everything that is not a sale: bills, other income, the cashbook and the ledger.",
    steps: [
      {
        id: "expenses",
        title: "Expenses, income and the cashbook",
        summary: "What the shop spends and takes that has nothing to do with selling.",
        screen: "/tenant/expenses",
        module: "expenses",
        required: "module",
        what: [
          "Rent, salaries, electricity, a chai run — and other income like a rebate or scrap sale. Categories come from the trade when the shop is created.",
          "An expense can be linked to the DRAWER (money physically out of the till) or not. Only the linked ones affect a shift. A business with no till has no drawer: there, cash is simply how the bill was paid, and nothing is said about a shift.",
          "Recurring entries fall DUE and are posted by somebody — they never post themselves silently.",
          "The cashbook is the day-by-day version of all of it, and the ledger is the running balance underneath.",
        ],
        checks: [
          { do: "Record a cash expense against the open shift.", expect: "The drawer's expected cash falls by it, and it is on the Z-read as a payout." },
          { do: "Record a non-cash expense (a bank transfer).", expect: "It is in the books and the drawer does NOT move." },
          { do: "Set a recurring monthly bill and travel past its date.", expect: "It shows as DUE. It must not post itself — a bill that pays itself is a bug." },
          { do: "Check the totals with two shops in the system.", expect: "Each shop's totals are its own. A total that sums every tenant is a defect this product has had." },
        ],
      },
      {
        id: "books-only",
        title: "A business that only keeps books",
        summary: "A Finance Manager — an office, an agency, a school — bought the books and nothing else. Nothing on its screens may talk to it as a shop with a till.",
        screen: "/tenant",
        module: "expenses",
        required: "module",
        what: [
          "This is the one trade that sells nothing. The admin's form offers it two modules — Expense & Income (needed) and Basic HR — and folds the other nineteen away. Its whole menu is eleven screens: Dashboard, Cashbook, Ledger, Income, Expenses, Reports, Staff, Activity, Subscription, Settings, Help.",
          "Every screen asks two questions of the business's MODULES, never of its trade's name: does it have a till, and does it sell. A Finance Manager given the till later has a drawer from that moment.",
          "It is called a business, not a shop: on Setup, the rail (\u201cYour business\u201d), Subscription and Settings.",
          "Its income is ALL typed by hand, so Income is \u201ceverything the business takes in\u201d and it starts with categories for what it earns: Client Payments, Service Fees, Sales, Commission, Donations & Grants.",
          "The only two things that can ever need it are a recurring bill that has fallen DUE and a category that has gone past its ceiling. Both are on its dashboard — in the line at the top and as rows that open the tab that deals with them.",
        ],
        checks: [
          { do: "As the admin, create a Finance Manager business on Basic and leave the modules as proposed.", expect: "The form says \u201ca books-only business\u201d, never \u201ca finance manager shop\u201d. Two switches are shown and nineteen are folded away." },
          { do: "Sign in as its owner and finish setup.", expect: "It is asked where its BUSINESS is, on the map as well. The dashboard says the books are empty, in the line at the top AND in the panel under it; the four tiles are Record income, Record expense, Reports, Cashbook; the figures open on This month." },
          { do: "Open Full view and read the menu. Then type /tenant/pos, /tenant/products and /tenant/sales into the address bar.", expect: "Eleven screens. Each typed address goes back to the dashboard, and nothing is refused on the way — open the Network tab and check there is no 403." },
          { do: "Record an income entry and a bill, both paid in Cash.", expect: "The lists say \u201cCash\u201d, not \u201cCash (to till)\u201d / \u201cCash (from till)\u201d. Each saves and says it was recorded. NOTHING about a shift or a drawer, anywhere." },
          { do: "Add a monthly recurring bill first due yesterday, then open the dashboard.", expect: "\u201c1 bill has fallen due and is waiting to be posted.\u201d Press its row: you land on the Recurring tab. Post it at a different figure: the expense is dated the day it was DUE, the next one is a month on from that date, and the usual figure has not changed." },
          { do: "Set a ceiling on a category and file a bill that goes past it.", expect: "It SAVES, and the form stays to say by how much. The dashboard then names the category, and its row opens the Budgets tab." },
          { do: "Open the Cashbook.", expect: "Five columns: Date, Income, Expenses, Net, Running net — no Sales, no Refunds, and nothing about the POS. The date menu offers Today, This Week, This Month, This Year, the Tax Year, last month and a custom range. Open ledger carries the window." },
          { do: "Open the Ledger for today alone.", expect: "Two chips, Income and Expenses. The opening balance is what everything before today came to. There is no \u2715 on the period. Search for nonsense, then press Clear all: every line comes back and the period has not moved." },
          { do: "Compare Reports with the dashboard for this month.", expect: "Money In, Money Out and Net are equal to the rupee. Reports has no row of tabs, and the chart's days read \u201c1 Oct\u201d." },
          { do: "Open Subscription, then Settings.", expect: "Usage lists storage, branches and staff only. One branch of one reads \u201cAll 1 in use\u201d in amber, not \u201cFull\u201d in red. No commission card. Settings has no Online shop card and says nothing of invoices or a storefront." },
        ],
        wrong: [
          "The words till, drawer, shift, POS or \u201cyour shop\u201d anywhere a books-only business can read them.",
          "A column, chip, tab or usage row for something it cannot have — Sales, Refunds, Supplier paid, Products, Registers, Offline selling.",
          "The line at the top of the dashboard saying nothing needs you while the panel under it lists something.",
          "A bill that has fallen due, or a budget that has been passed, and nothing about it on the dashboard.",
          "\u201cClear all\u201d leaving a filter on, or the Ledger answering with an error when its period is cleared.",
          "The map on Settings drawn over the Save bar.",
        ],
      },
      {
        id: "reports",
        title: "Reports",
        summary: "The numbers an owner actually reads, and the rules behind them.",
        screen: "/tenant/reports",
        required: "always",
        what: [
          "Sales, margins, tax, top products, staff, stock valuation. Every one of them must be re-derivable from the sales underneath it — that is the test.",
          "Revenue is GROSS with refunds shown as their own line. The margin report is the exception and nets at line level, because it is keyed to the day of SALE and has no per-item refund column.",
          "The tax year here runs 1 July to 30 June, beside the calendar year. Both are offered; quarters are unchanged.",
        ],
        checks: [
          { do: "Ring a known set of sales, then read the sales report for that day.", expect: "The total equals what you rang. Do the arithmetic by hand once — this is the single most valuable hour a tester spends on this product." },
          { do: "Refund part of a sale and re-read.", expect: "Revenue stays gross, a refunds line appears with the amount, and profit has the refund taken off." },
          { do: "Read the same day on the dashboard, the cashbook, the Z-read and the sales report.", expect: "They agree. Where they cannot (gross vs net), the screen says which it is showing." },
          { do: "Switch to the tax year.", expect: "The window is 1 Jul – 30 Jun, and the figures inside it add up to the months it covers." },
        ],
      },
      {
        id: "dashboard-period",
        title: "The dashboard, asked about a period",
        summary: "Today, yesterday, a week, a month, a quarter, a year or any two dates — and every figure says which.",
        screen: "/tenant",
        required: "always",
        what: [
          "The dashboard has a period, shown as a heading directly above the figures: its name (Today, Last 7 days, This month…), what it is compared with, two arrows that step it a period at a time, and a menu with every range and a custom one.",
          "Everything that is a FLOW follows it: sales, refunds, expenses, profit, orders, customers, the chart, the spending breakdown, the leaders, what each branch took, what a chemist dispensed. Everything that is a STATE does not: low stock, what is owed, the order pipeline, the floor, the bay and the line at the very top of the page are what is true NOW.",
          "A period is compared with its LIKE: a day with the day before; the first nine days of a month with the first nine of the month before (not the nine days before the 1st, which are always the poorest); a whole month with the whole month before; anything else with the same number of days immediately before. The heading says which.",
          "One day is not a trend, so for a single day the chart draws the seven days ending on it and says so. A month is a point a day, a quarter a point a week, a year a point a month.",
          "A shop that sells opens on Today. A business that only keeps books opens on This month. The opening period is NOT written into the address, so a dashboard left open overnight is on the new day in the morning; any other period IS, so a refresh keeps it.",
        ],
        checks: [
          { do: "Open the dashboard.", expect: "The heading says Today · Compared with yesterday, the tiles say Today's Sales / Today's Profit, the later arrow is disabled, and the address has no dates in it." },
          { do: "Press the earlier arrow once.", expect: "Yesterday. The tiles now say Yesterday's Sales — no tile anywhere still says Today — and the figures are yesterday's. The line at the top of the page still talks about today." },
          { do: "Pick Last 7 days from the menu.", expect: "The tiles say Sales, Expenses, Profit with no day in the name; the chart is those seven days; the breakdown says Last 7 days. Add up the chart's days by hand once: they come to the Sales tile exactly." },
          { do: "Pick This month, on a day after the 1st.", expect: "The heading says what it is compared with — the same days of LAST month, e.g. \"compared with 1 – 9 Sep\" — and a customer who came three times this month is counted once." },
          { do: "Pick Last quarter, then This year.", expect: "The chart says \"a point a week\", then \"a point a month\". The bars behind the Sales tile say what one bar is." },
          { do: "Pick Custom range and choose two dates.", expect: "Nothing changes until Apply. After it, the heading is the two dates and how many days they are. Refresh the page: the same period, the same figures." },
          { do: "Pick Today from the menu again.", expect: "The dates leave the address. Choosing Today must un-pin, not pin today's date." },
          { do: "Compare one period with Reports → Sales for the same two dates.", expect: "The same total. Then ring a sale at 1 am: it belongs to the day before, on both screens." },
          { do: "Open the menu on a phone.", expect: "It opens inside the screen." },
        ],
        wrong: [
          "A tile reading \"Today's Sales\" while the heading says anything but Today.",
          "The chart's points not adding up to the tile above them.",
          "The line at the top of the page, low stock, or what is owed changing when the period changes — those are about now.",
        ],
      },
    ],
  },

  {
    id: "people",
    title: "People, branches and trades",
    blurb: "Who works here, where, and what a shop of this kind gets that others do not.",
    steps: [
      {
        id: "staff",
        title: "Staff and permissions",
        summary: "There are no job roles in this product. A job is a set of permissions.",
        screen: "/tenant/staff",
        required: "always",
        what: [
          "Adding a cashier means granting the permissions a cashier needs. There are PRESETS — cashier, waiter, kitchen, stock keeper — but they are shortcuts that fill in a set, not roles with rules of their own.",
          "This matters for testing: every question about what somebody can do is answered by the permission list on their own record, and nowhere else.",
          "A staff member belongs to a BRANCH. That is which stock their till sells from, so it is not a cosmetic field.",
          "Activity is the audit trail — who changed what, including the things that move money like a credit limit.",
        ],
        checks: [
          { do: "Create a staff member with the Cashier preset.", expect: "Every screen the preset needs is reachable and every screen it does not is refused — both, from the same login. A job offered whose screens all bounce is a defect this product has had." },
          { do: "Change somebody's branch, sign in as them and ring a sale.", expect: "Stock moves in the NEW branch." },
          { do: "Change a customer's credit limit, then open Activity.", expect: "The change is there with the old and new value. A permission change being logged while a money change is not was a real defect." },
        ],
      },
      {
        id: "branches",
        title: "Branches",
        summary: "A shop with more than one site. Most of the hard bugs in this product live here.",
        screen: "/tenant/branches",
        required: "optional",
        what: [
          "Every shop has one branch called Main from the moment it exists, even if it never adds another. The Branches screen only appears once the shop's plan allows more than one.",
          "Stock, tills, shifts, days and prices can all be per-branch. A transfer moves stock between them.",
          "The header says which branch you are operating. Nearly every wrong-branch bug in this product's history has been a screen that ignored it.",
        ],
        checks: [
          { do: "Add a second branch, put stock in it, and switch to it in the header.", expect: "Stock, sales and reports all follow the switch." },
          { do: "Adjust stock while operating branch two.", expect: "Branch two moves. Adjustments always landing on Main is a defect this product has had." },
          { do: "Transfer stock from one branch to the other.", expect: "One falls by exactly what the other rises by." },
        ],
      },
      {
        id: "trades",
        title: "What each trade gets that others do not",
        summary: "The screens that exist for one kind of shop. Do not report them missing elsewhere.",
        required: "trade",
        what: [
          "PHARMACY — a dispensing register, batches with expiry (a medicine batch MUST have one), oldest-expiring sold first, near-expiry alerts, and prescription capture. Schedule-controlled medicine is refused through every door, not just the till.",
          "AUTOMOTIVE — vehicles by number plate with a service history, a bay board of cars taken in, trade-in as a TENDER (not a discount), and DOT date reading on tyres so the oldest stock goes first.",
          "PETROLEUM — tanks, pumps and nozzles, a forecourt shift that reads every meter and dips every tank, tanker deliveries, and rates that must not reprice a pump before the day they start.",
          "FOOD — dishes with recipes and per-size recipes, modifiers, the kitchen pass and dine-in.",
          "SERVICES — labour billed with or without a catalog, and a public portfolio.",
          "FINANCE — a books-only office: no till, no catalog, no stock. It still keeps a cashbook, and that is the whole product for them.",
        ],
        checks: [
          { do: "Open a shop of each trade you have access to and read its sidebar.", expect: "Each gets its own daily screen — the pass for a restaurant, the bay board for a workshop, the register for a chemist, the forecourt for a station." },
          { do: "Try to add a medicine batch with no expiry date.", expect: "Refused. For a chemist an expiry is not optional." },
          { do: "Look for Dine-in on a pharmacy.", expect: "Not there, and that is correct. This is the TRADE axis, not a bug." },
        ],
      },
    ],
  },

  {
    id: "offline",
    title: "Selling with no internet",
    blurb: "The hardest part of this product to test, and the part a shop notices most.",
    steps: [
      {
        id: "offline-ready",
        title: "Getting a till ready",
        summary: "A device has to be registered and primed before it can trade through a cut.",
        screen: "/tenant/settings",
        module: "pos",
        required: "optional",
        what: [
          "The till keeps its own copy of the catalog, the barcodes, the tax rules and the shop's settings. Without that copy there is nothing to sell from.",
          "Each tablet is a DEVICE with a name. Name them: the offline report puts that name against every late sale, and three tills all reading 'Unnamed till' tell an owner nothing.",
          "It is best installed to the home screen. A browser tab holds its data far less reliably, and on an iPad it is the only thing that makes a real difference.",
        ],
        checks: [
          { do: "Open Settings → Point of Sale → the till devices panel.", expect: "This device is listed, can be named, and the readiness line says whether it can sell offline yet." },
          { do: "Let it finish its first sync.", expect: "It reports what it saved — products, barcodes, settings — and says plainly what it did NOT save (photos, past sales, reports)." },
        ],
      },
      {
        id: "offline-selling",
        title: "Trading through a cut",
        summary: "Pull the plug and keep selling. This can only be tested in a real browser.",
        screen: "/tenant/pos",
        module: "pos",
        required: "optional",
        what: [
          "With the line down the till keeps selling from its own copy. Each sale gets an OFF- slip number that is unique to that device, so two tills can never print the same one.",
          "A shift can be opened and counted out offline too. The Z-read is PROVISIONAL until the queue has drained, and the till says so.",
          "When the line returns the queue drains by itself. Sales are filed against the day they HAPPENED, not the day they arrived.",
          "A ticket parked while offline is parked on that till only, and the till says so — it cannot be picked up at another lane until the line is back.",
        ],
        checks: [
          { do: "Turn the network off in the browser's dev tools (not the wifi — the browser must believe it is offline), then reload the till.", expect: "It still opens, still lists products, and still lets you open a shift and sell." },
          { do: "Ring three sales and read the slip numbers.", expect: "All OFF-, all different, and the customer can be found by one of them later." },
          { do: "Count the drawer out, still offline.", expect: "Accepted, and the till says the figures are provisional until the queue drains." },
          { do: "Turn the network back on.", expect: "The badge counts down and empties. Every sale lands on the day it was rung." },
          { do: "Open Reports → Offline the next morning.", expect: "What came in late, from which till, what broke a rule, what landed after a day was closed (in rupees), which shifts ran with no server, and which tablets have the wrong clock." },
        ],
        wrong: [
          "A sale that reaches the server twice. Ring one, sync, then sync again — there must still be one sale.",
          "Stock going negative without the recount list on Reports → Offline naming the item. Two tills each selling the last carton is not a bug; not being told is.",
        ],
      },
    ],
  },

  {
    id: "settings",
    title: "Settings, one tab at a time",
    blurb: "What every switch is for, and whether a shop has to touch it. This is the section testers usually skip and should not.",
    steps: [
      {
        id: "settings-tabs",
        title: "The tabs, and who gets which",
        summary: "A shop is only shown the settings it can use.",
        screen: "/tenant/settings",
        required: "always",
        what: [
          "BUSINESS — name, contact, address and the map pin. Every shop has this, including a books-only office: it still puts its name on what it sends out. REQUIRED.",
          "YOUR MODULES — read-only, what this shop was given. Always there.",
          "TAX & DELIVERY — tax rates, whether prices include tax, and delivery charges. Only for a shop that sells something.",
          "POINT OF SALE — how the till behaves: whether a shift is required before selling, cash rounding, the drawer ceiling, note-by-note counting, blind close, idle lock, receipt printing, the kitchen's own sub-tab. Needs the till module.",
          "LOYALTY — how points are earned and redeemed. Needs the customer book, because there is nobody to award them to without one.",
          "RECEIPT — what the printed receipt says and shows, previewed live. Only for a shop that sells.",
          "HARDWARE — the counter's own kit: receipt printer, label printer, scanner, cash drawer. Needs the till.",
          "BARCODES — how labels are laid out. Follows the Labels module.",
        ],
        checks: [
          { do: "Open Settings on shops of different trades and modules.", expect: "The tabs differ, and no tab appears whose module is off. A books-only office being offered Point of Sale and Loyalty was a real defect." },
          { do: "Change one switch on each tab, save, and reload.", expect: "It sticks. Then check it actually DOES something — a switch nothing reads is a defect this product has had (an entire 'require an open shift' setting was read by nothing)." },
          { do: "Change the receipt settings.", expect: "The live preview changes with them, and a printed receipt matches the preview." },
        ],
        wrong: [
          "A setting that saves and changes no behaviour anywhere. Test the switch by its EFFECT, never by whether the save succeeded.",
        ],
      },
    ],
  },

  {
    id: "admin",
    title: "The admin console",
    blurb: "The platform side. This is where shops are created and where most of your test setup happens.",
    steps: [
      {
        id: "admin-dashboard",
        title: "The platform dashboard",
        summary: "What happened in a period, and what the platform is right now — on two separate rows.",
        screen: "/admin",
        required: "always",
        what: [
          "The first row is the PERIOD's, named in the heading above it: revenue collected (and how many payments), new tenants (and how many were kept from a demo), online orders (and what they came to), new customers. It opens on the last seven days — a single day of a platform paid by the month is mostly noughts.",
          "The second row, Right now, is what the platform IS: total tenants, active subscriptions, active riders. It does not move when the period does.",
          "The period is cut on the SERVER's calendar, like the billing ledger's date filter. The trend charts under it are the long view — twelve months of revenue, six of sign-ups — and say so; they do not follow the period.",
          "Staff without the billing permission are not shown the money: the revenue tile is absent, not zero.",
          "Every date on the console is the PLATFORM's day, not the day on the laptop it is opened on: Today and This month on Payments, the Audit log and Commission are the same Today and This month as here.",
        ],
        checks: [
          { do: "Open the console.", expect: "The heading says Last 7 days and what it is compared with. No dates in the address." },
          { do: "Pick This month, then step back with the arrow.", expect: "The first row changes to last month — the whole of it. The Right now row has not moved at all." },
          { do: "Record a payment for a shop, then read Today.", expect: "Revenue collected goes up by it and the payment count by one." },
          { do: "Hand out a demo shop from the landing page and read Today.", expect: "New tenants does NOT go up — a demo is not a business. Approve a Keep-this-shop request: \"1 kept from a demo\" appears under New tenants." },
          { do: "Sign in as platform staff without Billing.", expect: "There is no Revenue collected tile, and the row is three tiles wide with no gap." },
          { do: "Between midnight and 5am in Pakistan, pick Today here, then on Payments, then on the Audit log.", expect: "All three name the same date — the server's, which is still yesterday at that hour. One screen a day ahead of the others is a bug." },
        ],
      },
      {
        id: "admin-tenants",
        title: "Businesses, plans and billing",
        summary: "Creating a shop, giving it modules and limits, and what it pays.",
        screen: "/admin/tenants",
        required: "always",
        what: [
          "Creating a business asks four things in the order the decisions actually happen: who it is (name, type, city), what it can DO (modules), how big it is (branches, staff, lanes) and what it PAYS (plan).",
          "A plan decides price, ceilings and which modules a shop STARTS with. It is never the gate: what a shop may use is the shop's own list, so a renewal or a plan change can never take away something an admin granted.",
          "There is no payment gateway anywhere in this product. Billing is recorded, not collected.",
        ],
        checks: [
          { do: "Create a business of each trade.", expect: "Its modules are proposed for that trade and can be adjusted before saving. What you saved is what the shop then has." },
          { do: "Change a shop's plan.", expect: "Its modules do not move. A plan change silently revoking a module would be a serious bug." },
          { do: "Count the businesses on the console against the tenant list.", expect: "Demo shops are not counted as businesses. They were once, and it made the number wrong by more than half. The list's All is the dashboard's Total tenants plus the demos being tried — and no deleted shop is in it." },
          { do: "Delete a shop, then look for it in the list.", expect: "It is gone from the list. Tick Deleted: it is there, marked deleted, with every other deleted shop and nothing else — and its page offers Restore. Untick and the live shops are back." },
          { do: "Find a shop on no plan (Any plan → Not priced yet).", expect: "Its row says \"not priced yet\", not \"paid\" — it has paid nothing. A suspended shop says suspended whether or not it has a plan." },
          { do: "Read the chips above the list: Paid, No plan yet, In grace, Unpaid, Suspended.", expect: "They add up to All. A shop on no plan is counted under No plan yet and NOT under Paid — Paid is only shops that are on a plan and inside what they paid for. Press No plan yet: every row says \"not priced yet\"." },
          { do: "Open a shop on a plan with an add-on and press Renew.", expect: "Under Amount it says what this shop owes for a month — its plan plus its add-ons — and offers to use it. Choose a different plan in the dialog: the figure follows the plan chosen, and says it is that plan's price only when the add-ons cannot be known yet." },
          { do: "Type an amount and a reference in Renew, close it without saving, and open it again.", expect: "It is empty again, with today's date. Nothing typed for one renewal is waiting inside the next." },
          { do: "Open any shop on a plan.", expect: "Under its name: what kind of shop, its city, since when. Then four figures before anything else — its plan and price, when it renews (amber in the last week; \"Today\" on the day), what it pays with its add-ons, how many branches, staff and checkout lanes it has." },
          { do: "Press Payments in the row of buttons under those figures, then Modules.", expect: "The page goes to that part and the buttons come with it; the part you asked for starts below them, not underneath." },
          { do: "Open every screen on the console's menu in turn.", expect: "Each has ONE heading at the top saying which screen it is, with its own icon. None opens on a bare table." },
        ],
      },
      {
        id: "admin-billing",
        title: "Billing & Payments: asked about a period",
        summary: "What came in over a period, what is late right now, and the ledger those figures are made of.",
        screen: "/admin/payments",
        required: "always",
        what: [
          "The screen has ONE period at its head — the same control the dashboards have, with the two arrows beside it. It opens on This month (the 1st up to today, by the server's calendar), because what is paid by the month is read by the month.",
          "Three figures follow the period: Collected, Payments, and Shops that paid — each with how it compares with the like period before (the first ten days of October against the first ten of September, not against all of September).",
          "Money late, Chase today, Subscription health and Revenue to date do NOT follow it. They are what is true now, whatever period is being read.",
          "The ledger at the foot shows the period's payments and says so under its heading. It can be given dates of its own, or none — its date control and the cross on the Paid chip — and that does not move the period. Choosing a new period at the top puts the ledger back on it.",
        ],
        checks: [
          { do: "Open Billing & Payments.", expect: "The heading over the figures says This month, with its dates and what it is compared with. No dates in the address." },
          { do: "Read Collected, then the total at the top of the ledger.", expect: "The same number. The ledger's line says it is following the period above." },
          { do: "Pick Last month.", expect: "Collected, Payments and Shops that paid change to last month's — the whole of it. Money late has not moved by a rupee. The ledger lists last month's payments, and its total is Collected again." },
          { do: "Step back with the arrow, then refresh.", expect: "The month before that, and still that month after the refresh — the dates are in the address." },
          { do: "Under Last month, search the ledger for a shop that only paid this month.", expect: "\"No payment in Last month matches — it may be on another date\", with a Search every date button. Press it: the payment is there, the line says every payment is being shown, and the period at the top is STILL Last month." },
          { do: "Press the cross on the Paid chip.", expect: "The ledger shows every date and its total says all time. The period and its three figures have not changed." },
          { do: "Record a payment for a shop dated today, then come back.", expect: "Collected is up by it, Payments by one, and Shops that paid by one only if that shop had not already paid this month." },
          { do: "Open the screen on a phone.", expect: "Collected has the width to itself with the two counts side by side under it. The period menu opens inside the screen; nothing scrolls sideways." },
        ],
        wrong: [
          "A figure that changes with the period when it is a state — Money late for last month is not a thing.",
          "Collected and the ledger's total disagreeing for the same dates.",
          "A search under a period that finds nothing and says only that nothing matches — it reads as \"this shop never paid\".",
        ],
      },
      {
        id: "admin-demo-shops",
        title: "Demo shops: trying, asking, kept",
        summary: "Every demo opened from the front page, and the two ways one becomes a real shop.",
        screen: "/admin/shop-requests",
        required: "always",
        what: [
          "\"Try the demo\" on the front page gives each visitor a shop of their own for a day. It has a generated name (Mart Demo K7QP), nobody can sign in to it — it is entered by the link and nothing else — and it clears itself away after a day.",
          "The screen has two lists. Asked to stay is the queue: visitors who pressed Keep this shop and typed their own sign-in, oldest first. Trying it now is every other demo, newest first, with what has been done in it — how much is on the shelf and how many sales were rung.",
          "A demo becomes a real shop in two ways, and both do exactly the same to it. Approve says yes to the owner's own request. Make it a real shop is the admin keeping it for them, there and then — for somebody from the platform sitting beside a shopkeeper who has just said yes — and it asks for the sign-in the owner will use, because a demo has none.",
          "Kept either way it is the SAME shop: its items, prices and sales stay. It goes back through the setup steps so the owner names their own business and drops their own pin, it is on no plan until an admin gives it one, and it is found in the tenant list under Kept their shop.",
          "A demo's own page says it is one, above everything else, with the same button.",
        ],
        checks: [
          { do: "Open a demo from the front page in another browser, ring one sale, then open Demo shops → Trying it now.", expect: "It is at the top: its name, its trade, \"opened just now\", 1 sale with the amount, and how long it has left." },
          { do: "Press Make it a real shop and leave the owner's fields empty.", expect: "The button cannot be pressed. A name, an email and a password of eight characters are all needed." },
          { do: "Press Suggest one.", expect: "A password in three short parts with no letters or digits that sound alike, shown in plain text so it can be read out." },
          { do: "Use an email somebody already signs in with.", expect: "Refused in words, and the shop is still a demo." },
          { do: "Fill it in properly and keep it.", expect: "You land on the shop's page. It no longer says demo, it is no longer under Trying it now, and the dashboard's \"Trying it\" count is one fewer. Sign in as the owner with what you typed: it is their shop, with the shelf and the sale still in it, and it asks them to finish setting up." },
          { do: "Open another demo, press Keep this shop inside it and fill the form, then find it under Trying it now.", expect: "It says Asked to stay and offers Approve, not the form — they already chose their own password." },
          { do: "Open a demo's page from the tenant list (Origin → Trying a demo).", expect: "A banner says it is a demo, that nobody can sign in to it, and offers Make it a real shop." },
        ],
        wrong: [
          "A kept shop that is empty — it must be the one they built, never a new one.",
          "A kept shop already on a plan with a month to run. Nothing was paid.",
          "The owner unable to sign in with what the admin typed.",
        ],
      },
      {
        id: "admin-commission",
        title: "Commission: who owes the platform",
        summary: "The share of what the marketplace sold for each shop — what is not yet billed, what is billed and unpaid, and what came in.",
        screen: "/admin/commission",
        required: "always",
        what: [
          "A shop pays two things and they are never mixed: its PLAN (Billing & Payments) and COMMISSION — a percentage of each completed ONLINE order. A sale at the till earns the platform nothing. The rate is the platform's, unless a shop has been given one of its own; a rate of nought is a promise, a blank one follows the platform.",
          "What a shop owes is two piles. Not yet billed: commission earned on orders that are on no invoice. Billed, unpaid: invoices raised and not yet marked paid. Both are money on every row, and the list is ordered by the two together — the shop owing most is first.",
          "The four figures at the top are counted by the server over every shop, not off the page that is open. Not yet billed, Billed unpaid and On a rate of their own are also buttons that narrow the list — and pressing one does not change its own figure.",
          "Opening a shop shows its unbilled orders and its invoices. An invoice is raised for a PERIOD that is chosen, and the panel says how many orders and how much it would bill before the button is pressed. An invoice raised by mistake is withdrawn with a reason — its orders are owed again. A single charge can be written off, also with a reason.",
          "The platform rate and what it is charged on are at the foot of the page. They move every shop that has no rate of its own.",
        ],
        checks: [
          { do: "Complete an online order on a shop, then open Commission.", expect: "Not yet billed goes up by the rate × the goods (not the delivery fee, unless the platform says so), the shop moves up the list, and its row says 1 order." },
          { do: "Press the Not yet billed figure.", expect: "Only shops with something unbilled. The figure itself does not change. The address now carries the filter — refresh and it is still narrowed." },
          { do: "Open a shop and pick a period with no orders in it.", expect: "\"Nothing was earned in …\" and Raise invoice cannot be pressed." },
          { do: "Pick a period that holds its orders and raise the invoice.", expect: "The panel said how many orders and how much before you pressed; the invoice is for exactly that. The shop's Not yet billed empties and its Billed, unpaid shows the amount — and it is still near the top of the list." },
          { do: "Mark the invoice paid.", expect: "Collected this month goes up by it. Marking it paid twice is refused." },
          { do: "Raise another and withdraw it.", expect: "A reason is required. Withdrawn, its orders are not yet billed again; the invoice stays in the history marked withdrawn. A PAID invoice cannot be withdrawn." },
          { do: "Give one shop a rate of its own, then change the platform rate.", expect: "That shop's row says \"own\" and does not move with the platform; every other row does. On a rate of their own counts it." },
          { do: "With more than twenty-five shops, go to page two and then change a filter.", expect: "It starts again at page one." },
        ],
        wrong: [
          "A shop with unpaid invoices and nothing new shown as owing nothing.",
          "A figure at the top that changes when the list is narrowed by that same figure.",
          "An invoice for a different amount than the panel said it would be.",
        ],
      },
      {
        id: "admin-appearance",
        title: "The console's own Appearance",
        summary: "The platform console's colour and what its menu is painted in — chosen from the console, and worn by everybody on it.",
        screen: "/admin",
        required: "optional",
        what: [
          "A shop has always had Appearance: its colour, how far that colour reaches into the page, and whether its menu is the brand colour, white, tinted or dark. The console has the same canvas now — the tab on the right edge of every console screen, on a desktop-width screen.",
          "It is the PLATFORM's look: one, saved once, seen by every super admin and every member of platform staff. Only a super admin is shown the tab. Light or dark is separate — that is the header toggle, and is kept on the device for that person only.",
          "Untouched, the console is the house colour with its menu in it. Reset hands it back to exactly that.",
          "A choice is previewed on the real console behind the canvas. Nothing is saved until Save, and closing without saving puts back what was there.",
        ],
        checks: [
          { do: "Open the tab on the right edge and pick a colour and a sidebar.", expect: "The console behind the canvas changes at once — the menu, the band at the top, the buttons. Save is only enabled once something differs from what is stored." },
          { do: "Close the canvas without saving.", expect: "The console goes back to how it was." },
          { do: "Pick again, Save, and reload the page.", expect: "It opens in the new look straight away — not in the house blue for a moment first. Every console screen wears it." },
          { do: "Sign in as platform staff (not a super admin) on another browser.", expect: "They see the same look, and no Appearance tab." },
          { do: "Press Reset, then Save.", expect: "The house colour and the brand-coloured menu are back, for everybody." },
          { do: "Sign out.", expect: "The sign-in page is in the house colour, whatever the console is wearing." },
        ],
      },
      {
        id: "admin-customers",
        title: "Customers",
        summary: "The people who order from the shops: found, corrected, switched off.",
        screen: "/admin/customers",
        required: "always",
        what: [
          "A customer here is somebody with an account on the app, ordering from ANY shop. It is not one shop's own customer book (khata) — that belongs to the shop and is on the shop's side.",
          "The screen is the list: who they are, how many orders across every shop, what they have spent on DELIVERED orders, when they last ordered. It used to be a single form with no list at all — an account could be made and never found again.",
          "The figures above the list are counted by the server, not read off the page that is open. Two of them are buttons: Have ordered, and Switched off.",
          "An account that has never ordered can be removed (it was made by mistake). One that has ordered cannot — an order belongs to its customer, and removing them would take a sale out of a shop's history. It is switched off instead.",
        ],
        checks: [
          { do: "Make a customer with a name, a phone and a password.", expect: "They are at the top of the list straight away, marked Can sign in, with no orders yet. A name and a password with neither a phone nor an email cannot be created." },
          { do: "Search by part of the phone number.", expect: "Only that person. Then by name and by email." },
          { do: "Open them, set a new password, and sign in on the app with it.", expect: "The new password works and the old one does not. They were signed out everywhere." },
          { do: "Switch the account off.", expect: "They cannot sign in, the row says Switched off, and the Switched off figure goes up by one and leads to them." },
          { do: "Open a customer who has ordered.", expect: "The shops they ordered from are named, and there is no Remove account button — only Switch off." },
        ],
      },
    ],
  },

  {
    id: "reporting",
    title: "Reporting what you find",
    blurb: "How to write it up so it can be fixed rather than argued about.",
    steps: [
      {
        id: "how-to-report",
        title: "Before you file it",
        summary: "Three questions that resolve most reports before they are written.",
        required: "always",
        what: [
          "Ask the three axes first: is the MODULE on, does this TRADE have the screen, and does this PERSON hold the permission? Most first-week reports answer themselves here.",
          "Then ask whether the figure you disagree with is GROSS or NET, and which day it belongs to. Revenue is gross with refunds as their own line; a refund belongs to the day it was handed back.",
          "A count with no denominator is not evidence. 'Three screens are wrong' means nothing without 'out of how many I checked'.",
        ],
        checks: [
          { do: "Write the shop, the branch, the person, the screen and the exact time.", expect: "Somebody else can reproduce it without asking you a single question." },
          { do: "Say what you EXPECTED and where that expectation came from — a figure you added up by hand, another screen, or this walkthrough.", expect: "The report names the disagreement, not just the screen." },
          { do: "For anything about money, include the sales it should be derived from.", expect: "The fix can be checked against the same arithmetic you did." },
        ],
      },
    ],
  },
];
